"""Per-account news — AUTO-GENERATED by fetch_news.py. Do not hand-edit.
Provider: gdelt. Window: last 30 days. Generated: 2026-07-27 17:33Z.
"""

NEWS = {
    "HILLTOP HOLDINGS": {
        "title": "Hilltop Holdings Inc . Sells 5 , 366 Shares of Danaher Corporation $DHR",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://www.themarketsdaily.com/2026/07/27/hilltop-holdings-inc-sells-5366-shares-of-danaher-corporation-dhr.html",
        "image": ""
    },
    "NATIONSTAR MORTGAGE": {
        "title": "Master Sales - Columbia Star",
        "date": "2026-07-23",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.thecolumbiastar.com/articles/masters-sales-303/",
        "image": ""
    },
    "Texas Capital Bank": {
        "title": "Texas Capital Bancshares , Inc . ( NASDAQ : TCBIO ) Declares Quarterly Dividend of $0 . 36",
        "date": "2026-07-23",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://www.themarketsdaily.com/2026/07/23/texas-capital-bancshares-inc-nasdaqtcbio-declares-quarterly-dividend-of-0-36.html",
        "image": ""
    },
    "WOODFOREST NATIONAL BANK": {
        "title": "Dunkin  planning new spot on Arthur Ashe , expanding presence in local Walmarts",
        "date": "2026-07-17",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://richmondbizsense.com/2026/07/17/dunkin-planning-new-spot-on-arthur-ashe-expanding-presence-in-local-walmarts/",
        "image": "https://richmondbizsense.com/wp-content/uploads/2026/07/dunkin-Cropped.png"
    },
    "COMERICA INC": {
        "title": "⚾ Michael Massey 2 - run , 2 - out homer in 8th helps Royals beat Tigers",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://jcpost.com/posts/c39aa47a-9310-4de2-8ecc-0b7bfc7105e5",
        "image": "https://media.eaglewebservices.com/public/2026/7/1785102330575.png"
    },
    "Navient": {
        "title": "Netflix stock hits a 52 - week low after earnings but analysts say investors are missing the picture",
        "date": "2026-07-17",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://fortune.com/2026/07/17/netflix-stock-hit-52-week-low-after-earnings-analysts-say-investors-missing-big-picture-cfo/",
        "image": "https://fortune.com/img-assets/wp-content/uploads/2026/07/GettyImages-2285761545.jpg"
    },
    "NORTHWEST SAVINGS BANK": {
        "title": "Social Security Matters : Can spouse file at 63 , get half of mine when I claim later ?",
        "date": "2026-07-17",
        "summary": "",
        "impact": "Potential Security opportunity — align outreach to this signal.",
        "level": "Medium",
        "url": "https://www.bradfordera.com/2026/07/17/social-security-matters-can-spouse-file-63-get-half-mine-claim-later/",
        "image": "https://www.bradfordera.com/bradfordera/news/wp-content/uploads/sites/4/2025/08/OPED-SOCIAL-SECURITY-REFORM-EDITORIAL-DMT-1024x683.jpg"
    },
    "EAST WEST BANCORP INC": {
        "title": "A $550 , 000 Portfolio That Quietly Pays a 62 - Year - Old $3 , 400 a Month Until Social Security Kicks In",
        "date": "2026-07-26",
        "summary": "",
        "impact": "Potential Security opportunity — align outreach to this signal.",
        "level": "Medium",
        "url": "https://finance.yahoo.com/markets/stocks/articles/550-000-portfolio-quietly-pays-195234765.html",
        "image": "https://s.yimg.com/lo/mysterio/api/D93A779C2268C84632CE83FC12B9C4A2CFF9B26BDC1B60E26B27BDB98A5EBD73/subgraphmysterio/resizefill_w1200_h633;quality_80;format_webp/https:%2F%2Fmedia.zenfs.com%2Fen%2F24_7_wall_st__718%2F1971681c16df76d900f15c765694dead"
    },
    "Midland Credit Management": {
        "title": "Master Sales - Columbia Star",
        "date": "2026-07-23",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.thecolumbiastar.com/articles/masters-sales-303/",
        "image": ""
    },
    "MORTGAGE RESEARCH CENTER": {
        "title": "Current refi mortgage rates report for July 24 , 2026",
        "date": "2026-07-24",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://fortune.com/article/current-refi-mortgage-rates-07-24-2026/",
        "image": "https://fortune.com/img-assets/wp-content/uploads/2026/07/Refi-Rates-July-24.jpg"
    },
    "PINNACLE BANK": {
        "title": "Cheba Hut Plants Its Flag in Nebraska With First - Ever Lincoln Joint",
        "date": "2026-07-22",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.restaurantnewsrelease.com/cheba-hut-plants-its-flag-in-nebraska-with-first-ever-lincoln-joint/",
        "image": "https://www.restaurantnewsrelease.com/wp-content/uploads/2026/07/Cheba-Hut-Toasted-Subs-Lincoln-Nebraska-feature.jpg"
    },
    "WESTERN UNION": {
        "title": "Foxconn drops VMware , adopts hyperconverged upstart Arcrfra for workloads including AI",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Potential Azure AI opportunity — align outreach to this signal.",
        "level": "Medium",
        "url": "https://www.theregister.com/virtualization/2026/07/27/foxconn-drops-vmware-adopts-hyperconverged-upstart-arcrfra-for-workloads-including-ai/5278684",
        "image": "https://image.theregister.com/253902.jpg?imageId=253902&x=0&y=0&cropw=100&croph=100&panox=0&panoy=0&panow=100&panoh=100"
    },
    "Guaranteed Rate Inc": {
        "title": "Method to cheaper Ryanair flights that hiding in plain sight",
        "date": "2026-07-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.somersetlive.co.uk/whats-on/whats-on-news/method-cheaper-ryanair-flights-thats-11078536",
        "image": "https://i2-prod.galwaybeo.ie/news/galway-news/article11078531.ece/ALTERNATES/s1200/2_Ryanair-Boeing-737-800-airplane-at-Rhodes-airport-in-Greece.jpg"
    },
    "Old National Bancorp": {
        "title": "Old National Bancorp ( NASDAQ : ONB ) Announces Quarterly Earnings Results",
        "date": "2026-07-24",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://www.themarketsdaily.com/2026/07/24/old-national-bancorp-nasdaqonb-announces-quarterly-earnings-results.html",
        "image": ""
    },
    "TRANS UNION CORPORATION": {
        "title": "@ wi . bopm Webinar June 30 , 2026 : No . U . S . War On Cuba ! Why Queer People Should Stand With Cuba Against Trump Attacks ! – Wisconsin Bail Out the People Movement",
        "date": "2026-06-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://wibailoutpeople.org/2026/06/27/wi-bopm-webinar-june-30-2026-no-u-s-war-on-cuba-why-queer-people-should-stand-with-cuba-against-trumps-attacks/",
        "image": "https://i0.wp.com/wibailoutpeople.org/wp-content/uploads/2026/06/image-234.png?fit=927%2C1200&ssl=1"
    },
    "ZIONS BANK CORPORATION": {
        "title": "Northern Utah Living : 3 events to check out this week ( July 25 - Aug . 2 ) | News , Sports , Jobs",
        "date": "2026-07-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.standard.net/lifestyle/2026/jul/25/northern-utah-living-3-events-to-check-out-this-week-july-25-aug-2/",
        "image": "https://ogden_images.s3.amazonaws.com/www.standard.net/images/2025/07/31212147/BW_Korn-Ferry-Golf_-020-1200x801.jpg"
    },
    "ARVEST BANK GROUP": {
        "title": "Sei Investments Co . Acquires 846 , 230 Shares of Exelon Corporation $EXC",
        "date": "2026-07-24",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://www.tickerreport.com/banking-finance/13513858/sei-investments-co-acquires-846230-shares-of-exelon-corporation-exc.html",
        "image": ""
    },
    "EXETER FINANCE CORP": {
        "title": "Commentary :  What are the Trail Blazers worth to Portland and Oregon ?",
        "date": "2026-07-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://portlandtribune.com/2026/07/23/commentary-what-are-the-trail-blazers-worth-to-portland-and-oregon/",
        "image": "https://portlandtribune.com/wp-content/uploads/sites/20/2026/07/blazers-generic.jpg"
    },
    "Movement Mortgage": {
        "title": "Power Moves : CBRE , MBA , TMO and others make key personnel decisions",
        "date": "2026-07-24",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.scotsmanguide.com/news/power-moves-july-6-to-24/",
        "image": "https://www.scotsmanguide.com/files/sites/2/2026/07/Power-Moves-July-6-to-24.jpg"
    },
    "REGIONS FINANCIAL CORPORATION": {
        "title": "TIME names 7 Alabama companies among America best for 2026",
        "date": "2026-07-22",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Medium",
        "url": "https://finance.yahoo.com/markets/stocks/articles/time-names-7-alabama-companies-191334112.html",
        "image": ""
    },
    "Global Payments": {
        "title": "Visa ( V ) Reports Q2 : Everything You Need To Know Ahead Of Earnings",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://finance.yahoo.com/markets/stocks/articles/visa-v-reports-q2-everything-054902456.html",
        "image": "https://s.yimg.com/lo/mysterio/api/89E0AF29FC94CB0C9DF92A4861D986D262919E529320941C57915CBC65641680/subgraphmysterio/resizefill_w1200_h600;quality_80;format_webp/https:%2F%2Fmedia.zenfs.com%2Fen%2Fstockstory_922%2Fa5611014185f275daf30f6ca736e6406"
    },
    "Sagent M&C, LLC": {
        "title": "The Inner Circle acknowledges Connie L . Doyle as a 2026 Pinnacle Professional Member Inner Circle of Excellence",
        "date": "2026-06-30",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.prnewswire.com/news-releases/the-inner-circle-acknowledges-connie-l-doyle-as-a-2026-pinnacle-professional-member-inner-circle-of-excellence-302814783.html",
        "image": "https://mma.prnewswire.com/media/3002553/The_Inner_Circle__Connie_L_Doyle.jpg?p=facebook"
    },
    "APPLIED SYSTEMS INC": {
        "title": "The Truth Behind The Iconic Look : Is Mary Ann Esposito Hair Real Or A Well - Kept Secret ?",
        "date": "2026-07-24",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.unitaid.eu/iconic-look-mary-ann-esposito-8n8c.html",
        "image": "https://www.unitaid.eu/Themes/agk/assets/agk.jpg"
    },
    "Insurity": {
        "title": "Insurity Expands Access to Advanced Risk Intelligence Through Partnership with Confianza",
        "date": "2026-07-21",
        "summary": "",
        "impact": "Potential Security opportunity — align outreach to this signal.",
        "level": "Medium",
        "url": "https://thestarphoenix.com/press-releases/business-wire/insurity-expands-access-to-advanced-risk-intelligence-through-partnership-with-confianza/",
        "image": "https://cts.businesswire.com/ct/CT?id=bwnews&sty=20260721379468r1&sid=cnpm5&distro=ftp"
    },
    "Q2 Software": {
        "title": "IBM insists AI didnt kill software deals , just delayed them",
        "date": "2026-07-23",
        "summary": "",
        "impact": "Potential Azure AI opportunity — align outreach to this signal.",
        "level": "High",
        "url": "https://www.theregister.com/software/2026/07/23/ibm-insists-ai-didnt-kill-software-deals-just-delayed-them/5276977",
        "image": "https://image.theregister.com/241548.jpg?imageId=241548&x=0&y=0&cropw=100&croph=100&panox=0&panoy=0&panow=100&panoh=100"
    },
    "ALLY FINANCIAL": {
        "title": "SYF vs . ALLY vs . COF : Which Consumer Finance Stock Is the Best Buy After Earnings ?",
        "date": "2026-07-25",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://finance.yahoo.com/markets/stocks/articles/syf-vs-ally-vs-cof-123637415.html",
        "image": "https://s.yimg.com/lo/mysterio/api/3581404FDE04019352B0BFCCB89AE4DBAA4C56598A3037C80F321A54BF26A5BE/subgraphmysterio/resizefill_w1200_h906;quality_80;format_webp/https:%2F%2Fmedia.zenfs.com%2Fen%2Finsidermonkey.com%2F89c1c0a0ea9fa92c580cfa144be9f66f"
    },
    "State Employees Credit Union": {
        "title": "Jackpotting  thieves get ATMs to spit out stacks of cash in Washington and Oregon",
        "date": "2026-06-29",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "http://www.chronline.com/stories/jackpotting-thieves-get-atms-to-spit-out-stacks-of-cash-in-washington-and-oregon,404703",
        "image": "https://gamma.creativecirclecdn.com/lafromboise/original/20210304-162046-sirens.jpg"
    },
    "SYNOVUS FINANCIAL CORP": {
        "title": "Bank M & A slowed to a crawl after start of the Iran war",
        "date": "2026-07-14",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.americanbanker.com/news/bank-m-a-slowed-to-a-crawl-after-start-of-the-iran-war",
        "image": "https://source-media-brightspot.s3.us-east-1.amazonaws.com/df/7c/d96499504243aab4cc7e2a6dd809/bank-m-a-deals-1h26-16x9.png"
    },
    "DOVENMUEHLE MORTGAGE INC": {
        "title": "News : Dovenmuehle Mortgage names Ann Morey its head of product",
        "date": "2026-07-05",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Medium",
        "url": "https://enewschannels.com/news-dovenmuehle-mortgage-names-ann-morey-its-head-of-product-3/",
        "image": "https://enewschannels.com/META/21-news-from-enewschannels-800x600.jpg"
    },
    "Select Portfolio Servicing, Inc.": {
        "title": "July 23 , 2026",
        "date": "2026-07-24",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.birminghamtimes.com/2026/07/july-23-2026/",
        "image": "https://www.birminghamtimes.com/wp-content/uploads/2024/05/AdobeStock_1679179941.jpeg"
    },
    "Flagstar Bank": {
        "title": "Flagstar Bank , National Association ( NYSE : FLG ) Releases Earnings Results , Misses Expectations By $0 . 01 EPS",
        "date": "2026-07-25",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://www.dailypolitical.com/2026/07/25/flagstar-bank-national-association-nyseflg-releases-earnings-results-misses-expectations-by-0-01-eps.html",
        "image": ""
    },
    "FREDDIE MAC": {
        "title": "Inflation is slashing middle - class incomes . Here where it worst",
        "date": "2026-07-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://finance.yahoo.com/economy/articles/inflation-slashing-middle-class-incomes-130000667.html",
        "image": "https://s.yimg.com/lo/mysterio/api/68FDA32EA37C013A7B6FB6021D951F90560E3924432B713E5BFB15146E49F73B/subgraphmysterio/resizefill_w1200_h800;quality_80;format_webp/https:%2F%2Fmedia.zenfs.com%2Fen%2Fthe_hill_articles_341%2F229ff9d5a7f3de26cf86c2c464c6ff4f"
    },
    "Synchrony Financial": {
        "title": "Sei Investments Co . Has $57 . 41 Million Position in Synchrony Financial $SYF",
        "date": "2026-07-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.themarketsdaily.com/2026/07/26/sei-investments-co-has-57-41-million-position-in-synchrony-financial-syf.html",
        "image": ""
    },
    "WEBSTER BANK": {
        "title": "CVR Partners ( NYSE : UAN ) Share Price Passes Above 200 - Day Moving Average – Should You Sell ?",
        "date": "2026-07-25",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Medium",
        "url": "https://www.dailypolitical.com/2026/07/25/cvr-partners-nyseuan-share-price-passes-above-200-day-moving-average-should-you-sell.html",
        "image": ""
    },
    "FIFTH THIRD BANCORP": {
        "title": "The Gabelli Global Small and Mid Cap Value Trust ( NYSE : GGZ ) Shares Cross Below 50 Day Moving Average – Here Why",
        "date": "2026-07-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.themarketsdaily.com/2026/07/26/the-gabelli-global-small-and-mid-cap-value-trust-nyseggz-shares-cross-below-50-day-moving-average-heres-why.html",
        "image": ""
    },
    "FIRST HORIZON BANK": {
        "title": "EnerCom Releases Presenter Lineup for the 31st EnerCom Denver - The Energy Investment Conference , August 17 – 19 , 2026 , in Denver , Colorado",
        "date": "2026-07-25",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.oilandgas360.com/enercom-releases-presenter-lineup-for-the-31st-enercom-denver-the-energy-investment-conference-august-17-19-2026-in-denver-colorado-2/",
        "image": "https://www.oilandgas360.com/wp-content/uploads/2026/07/OAG360-Featured@2x-Register2026-1.png"
    },
    "HEALTHEQUITY INC": {
        "title": "Investment Analyst Upgrades for July 25th ( ACIW , ACRE , AEE , AGI , AKAN , ALNY , AMACU , AMBP , APOG , ARCC )",
        "date": "2026-07-25",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.tickerreport.com/banking-finance/13515757/investment-analysts-upgrades-for-july-25th-aciw-acre-aee-agi-akan-alny-amacu-ambp-apog-arcc.html",
        "image": ""
    },
    "loanDepot": {
        "title": "Padres sweep Marlins , strengthening their outlook before the Trade Deadline",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.mlb.com/padres/news/manny-machado-jackson-merrill-hit-homers-padres-sweep-marlins",
        "image": "https://img.mlbstatic.com/mlb-images/image/upload/t_2x1/t_w1536/mlb/x5vxjxhlhuy2uezwef3h.jpg"
    },
    "DUCK CREEK TECHNOLOGIES INC": {
        "title": "Duck Creek Acquires Send , Creating the Industry Only Agentic Underwriting - to - Core Platform",
        "date": "2026-07-07",
        "summary": "",
        "impact": "Potential Fabric opportunity — align outreach to this signal.",
        "level": "High",
        "url": "http://www.singaporestar.com/news/279172562/duck-creek-acquires-send-creating-the-industry-only-agentic-underwriting-to-core-platform",
        "image": ""
    },
    "Elevate Credit": {
        "title": "Fort Worth - Based Elevate Closes $655 Million Credit Facility to Fuel Next Phase of Growth",
        "date": "2026-07-13",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://fortworthbusiness.com/business/fort-worth-based-elevate-closes-655-million-credit-facility-to-fuel-next-phase-of-growth/",
        "image": ""
    },
    "FACTSET RESEARCH SYSTEMS": {
        "title": "Compass Rose Asset Management LP Takes Position in FactSet Research Systems Inc . $FDS",
        "date": "2026-07-24",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.themarketsdaily.com/2026/07/24/compass-rose-asset-management-lp-takes-position-in-factset-research-systems-inc-fds.html",
        "image": ""
    },
    "Jack Henry & Associates Inc.": {
        "title": "IBM upgrades Bob with multi - agent tools & analytics",
        "date": "2026-07-21",
        "summary": "",
        "impact": "Potential Fabric opportunity — align outreach to this signal.",
        "level": "Medium",
        "url": "https://itbrief.co.nz/story/ibm-upgrades-bob-with-multi-agent-tools-analytics",
        "image": ""
    },
    "FANNIE MAE": {
        "title": "Mortgage and refinance interest rates today , Friday , July 24 , 2026 : Dropping below 6 . 5 %",
        "date": "2026-07-25",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://finance.yahoo.com/personal-finance/mortgages/article/mortgage-and-refinance-interest-rates-today-friday-july-24-2026-dropping-below-65-100000803.html",
        "image": "https://s.yimg.com/lo/mysterio/api/FE29947F7E4012BB2172DF695EC837536EB9CA82DC1820A61AA1A3CCA14D6ED0/subgraphmysterio/resizefill_w1200_h675;quality_80;format_webp/https:%2F%2Fs.yimg.com%2Fos%2Fcreatr-uploaded-images%2F2024-04%2Fc36fbdb0-0289-11ef-be8f-4e0451f1fa09"
    },
    "FIRST CITIZENS BANK & TRUST COMPANY": {
        "title": "First Citizens Bank & Trust Co . Makes New Investment in Vail Resorts , Inc . $MTN",
        "date": "2026-07-25",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.tickerreport.com/banking-finance/13515016/first-citizens-bank-trust-co-makes-new-investment-in-vail-resorts-inc-mtn.html",
        "image": ""
    },
    "VYSTAR CREDIT UNION": {
        "title": "New  Duuuval Wall mural opens in historic Union Terminal",
        "date": "2026-07-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.actionnewsjax.com/news/local/new-mural-jam-duuuval-walls-opens-historic-downtown-jacksonville-tunnel/LQ2BVISFGBHLFLVJ3FETCC3ITA/",
        "image": "https://cmg-cmg-tv-10050-prod.cdn.arcpublishing.com/resizer/v2/https%3A%2F%2Fcloudfront-us-east-1.images.arcpublishing.com%2Fcmg%2FC7IUKTODZNAWTHQ6GFH2XG4LDU.jpeg?auth=5918317d07c010f1c0d49b92cb05fde6958b24bdbcb163380da3655f1b8230d4&smart=true"
    },
    "CITIZENS FINANCIAL GROUP": {
        "title": "Disclosures show CFPB pick ties to several regulated firms",
        "date": "2026-07-25",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.americanbanker.com/news/disclosures-show-cfpb-picks-ties-to-several-regulated-firms",
        "image": "https://source-media-brightspot.s3.us-east-1.amazonaws.com/df/0c/a24bee6d4db28bc4eed69f8ebe2b/johnsoncfpb.png"
    },
    "United Wholesale Mortgage": {
        "title": "UWM fires back at Rocket in first salvo of $100M lawsuit",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.nationalmortgagenews.com/news/uwm-fires-back-at-rocket-in-first-salvo-of-100m-lawsuit",
        "image": "https://source-media-brightspot.s3.us-east-1.amazonaws.com/97/92/2f3042444c65baeb3979e4937e75/nmn-og-image.jpg"
    },
    "NAVY FEDERAL CREDIT UNION M": {
        "title": "What are VA loan rates today , July 24 , 2026 and the best lenders",
        "date": "2026-07-24",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.cnbc.com/select/what-are-va-loan-rates-today-july-24-2026/",
        "image": "https://image.cnbcfm.com/api/v1/image/108336658-1784299122906-gettyimages-2203659327-sandyrobertk2_055.jpeg?v=1784299145"
    },
    "FISERV Inc": {
        "title": "Frank Bisignano : Were bringing Social Security and IRS into the future",
        "date": "2026-07-26",
        "summary": "",
        "impact": "Potential Security opportunity — align outreach to this signal.",
        "level": "Medium",
        "url": "https://www.baltimoresun.com/2026/07/26/frank-bisignano-were-bringing-social-security-and-irs-into-the-future/",
        "image": "https://www.baltimoresun.com/wp-content/uploads/2026/07/TBS-L-IRS-002.jpg"
    },
    "Wells Fargo & Company": {
        "title": "Goldman Sachs Access Inflation Protected USD Bond ETF ( BATS : GTIP ) Short Interest Down 74 . 9 % in July",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.dailypolitical.com/2026/07/27/goldman-sachs-access-inflation-protected-usd-bond-etf-batsgtip-short-interest-down-74-9-in-july.html",
        "image": ""
    },
    "US BANK": {
        "title": "Iran war escalation puts Federal Reserve in a bind",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.thenationalnews.com/business/economy/2026/07/27/iran-war-escalation-puts-federal-reserve-in-a-bind/",
        "image": "https://www.thenationalnews.com/resizer/v2/ZVQ2S33FS6E2YVAEIJOJV73G3I.jpg?smart=true&auth=2e7645cca0509270f73b0892c2c67c269214c0fea19586851216633134f794b5"
    },
    "STATE STREET BOSTON CORPORATION": {
        "title": "Top banker Sunita Kanchinadam Named 15th President of TiE Boston",
        "date": "2026-07-10",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://newsindiatimes.com/top-banker-sunita-kanchinadam-named-15th-president-of-tie-boston/",
        "image": "https://newsindiatimes.com/wp-content/uploads/2026/07/unnamed-90.jpg"
    },
    "BNY Mellon": {
        "title": "Offense & Defense : The Infrastructure ETF Playbook",
        "date": "2026-07-23",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://finance.yahoo.com/markets/stocks/articles/offense-defense-infrastructure-etf-playbook-161117481.html",
        "image": "https://s.yimg.com/lo/mysterio/api/6C0BA2F532EB0D334EC9321A23DAF71CC02A0206249195B9CFBED18397406365/subgraphmysterio/resizefill_w1200_h675;quality_80;format_webp/https:%2F%2Fmedia.zenfs.com%2Fen%2Fetftrends.com%2Ff9b387d9b385da5116118185d77a205f"
    },
    "JPMORGAN CHASE": {
        "title": "Check Point Software Technologies ( NASDAQ : CHKP ) Stock Rating Lowered by JPMorgan Chase & Co .",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Medium",
        "url": "https://www.dailypolitical.com/2026/07/27/check-point-software-technologies-nasdaqchkp-stock-rating-lowered-by-jpmorgan-chase-co.html",
        "image": ""
    },
    "Citigroup": {
        "title": "Oppenheimer Issues Pessimistic Forecast for Boston Scientific ( NYSE : BSX ) Stock Price",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.themarketsdaily.com/2026/07/27/oppenheimer-issues-pessimistic-forecast-for-boston-scientific-nysebsx-stock-price.html",
        "image": ""
    },
    "Capital One": {
        "title": "Mississippi teen accused of killing elderly couple was known to deputies before attack",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.fox35orlando.com/news/mississippi-teen-accused-killing-elderly-couple-was-known-deputies-before-attack",
        "image": "https://images.foxtv.com/static.livenowfox.com/www.livenowfox.com/content/uploads/2026/07/1280/720/screenshot-2026-07-26-072342.png?ve=1&tl=1"
    },
    "EDWARD D JONES AND COMPANY": {
        "title": "Edward Jones pushes back on lawsuit challenging diversity program",
        "date": "2026-07-09",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://finance.yahoo.com/small-business/articles/edward-jones-pushes-back-lawsuit-121800705.html",
        "image": "https://s.yimg.com/lo/mysterio/api/122F07CADD6BBC20623DB87F59E5D0C8E0499CE60AEB49632F5E33DFD1E93C88/subgraphmysterio/resizefill_w1200_h675;quality_80;format_webp/https:%2F%2Fmedia.zenfs.com%2Fen%2Fhr_dive_843%2F32b1dec6214085df10ced8550abee0d2"
    },
    "Apollo Management": {
        "title": "Ode with Anthropic and LogicGate Announce Partnership to Scale Expert - Led Client Outcomes through Accelerated Agentic Capabilities",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Medium",
        "url": "https://leaderpost.com/press-releases/business-wire/ode-with-anthropic-and-logicgate-announce-partnership-to-scale-expert-led-client-outcomes-through-accelerated-agentic-capabilities/",
        "image": "https://cts.businesswire.com/ct/CT?id=bwnews&sty=20260727617963r1&sid=cnpm5&distro=ftp"
    },
    "BAIN CAPITAL LLC": {
        "title": "Eightco Holdings ( NASDAQ : ORBS ) Announces its Participation in World Foundation $52 . 5M funding round as World Shifts From Building the Network to Scaling Utility",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://www.manilatimes.net/2026/07/27/tmt-newswire/pr-newswire/eightco-holdings-nasdaq-orbs-announces-its-participation-in-world-foundations-525m-funding-round-as-world-shifts-from-building-the-network-to-scaling-utility/2392190",
        "image": "https://manilatimes.net/manilatimes/uploads/images/2026/07/27/1152598.jpg"
    },
    "INVESCO": {
        "title": "SpaceX Stock Is Down 48 % From Its High . Here Why ETFs Are Loading Up Anyway .",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://finance.yahoo.com/markets/stocks/articles/spacex-stock-down-48-high-130600317.html",
        "image": "https://s.yimg.com/lo/mysterio/api/AA6B871863C23FE40EF13E6927654071E290D2DCBD7DDC5CAA6937F191B4B074/subgraphmysterio/resizefill_w1200_h675;quality_80;format_webp/https:%2F%2Fmedia.zenfs.com%2Fen%2Fmotleyfool.com%2Fdbd00e65159722aa6d6cb864d4eef783"
    },
    "LPL Financial": {
        "title": "Goldman Sachs Access Inflation Protected USD Bond ETF ( BATS : GTIP ) Short Interest Down 74 . 9 % in July",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.dailypolitical.com/2026/07/27/goldman-sachs-access-inflation-protected-usd-bond-etf-batsgtip-short-interest-down-74-9-in-july.html",
        "image": ""
    },
    "JEFFERIES & COMPANY INC": {
        "title": "Oppenheimer Issues Pessimistic Forecast for Boston Scientific ( NYSE : BSX ) Stock Price",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.themarketsdaily.com/2026/07/27/oppenheimer-issues-pessimistic-forecast-for-boston-scientific-nysebsx-stock-price.html",
        "image": ""
    },
    "FINRA": {
        "title": "Round - the - clock trading is coming , but retail investors are already there",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.investmentnews.com/equities/round-the-clock-trading-is-coming-but-retail-investors-are-already-there/267554",
        "image": "https://cdn-res.keymedia.com/investmentnews/uploads/2019/10/BLOG12_150909988_AR_-1_YTLKZWFZUQCV-2.jpg"
    },
    "MORNINGSTAR INC": {
        "title": "Meet the American techies who dont care where  good enough  AI models come from , even China",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Potential Azure AI, Fabric opportunity — align outreach to this signal.",
        "level": "Medium",
        "url": "https://fortune.com/2026/07/27/open-frontier-increasingly-chinese-built/",
        "image": "https://fortune.com/img-assets/wp-content/uploads/2026/07/AP26207087220843-e1785154826248.jpg"
    },
    "Fortress Investment Group": {
        "title": "Majestic puts the Champagne on ice as it prepares to toast arrival in Trowbridge",
        "date": "2026-07-24",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://retailtimes.co.uk/majestic-puts-the-champagne-on-ice-as-it-prepares-to-toast-arrival-in-trowbridge/",
        "image": ""
    },
    "TWO SIGMA INVESTMENTS": {
        "title": "Ecopetrol ( EC ) to Release Quarterly Earnings on Monday",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://www.themarketsdaily.com/2026/07/27/ecopetrol-ec-to-release-quarterly-earnings-on-monday.html",
        "image": ""
    },
    "Commonwealth Financial Network": {
        "title": "$1 Billion Team Joins Raymond James From Stifel",
        "date": "2026-07-24",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.wealthmanagement.com/ibd-news/1-billion-team-joins-raymond-james-from-stifel",
        "image": "https://eu-images.contentstack.com/v3/assets/bltabaa95ef14172c61/blte3facab7c0ab1995/6a627a894bce47b8e5f7939c/kwm-team-raymond-james.jpg?disable=upscale&fit=crop&overlay=%2Fv3%2Fassets%2Fbltabaa95ef14172c61%2Fblt38d05c932b77fe9f%2F6a3931f66deb92be88b595a5%2FWM-OpenGraph_indigo.png&overlay-width=432&overlay-height=166&overlay-align=right,bottom"
    },
    "JANUS HENDERSON GROUP": {
        "title": "AI spending surge puts Big Tech cash flows under pressure",
        "date": "2026-07-25",
        "summary": "",
        "impact": "Potential Azure AI opportunity — align outreach to this signal.",
        "level": "Medium",
        "url": "http://www.phoenixherald.com/news/279206172/ai-spending-surge-puts-big-tech-cash-flows-under-pressure",
        "image": "https://image.chitra.live/api/v1/wps/d8cd7cf/c6b5e4cb-f2e9-47b4-9d05-e67e8542aa26/1/Google-new-600x315.jpg"
    },
    "CARLYLE": {
        "title": "Katy Perry blasts White House for using hit song  Firework  she sold in $225M catalog deal",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://foxwilmington.com/katy-perry-blasts-white-house-for-using-hit-song-firework-she-sold-in-225m-catalog-deal/",
        "image": ""
    },
    "CERBERUS CAPITAL MANAGEMENT LP": {
        "title": "Eos Energy Announces Expiration and Results of Rights Offering",
        "date": "2026-07-23",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://www.manilatimes.net/2026/07/23/tmt-newswire/globenewswire/eos-energy-announces-expiration-and-results-of-rights-offering/2390326",
        "image": "https://manilatimes.net/manilatimes/uploads/images/2026/07/23/1148688.png"
    },
    "Berkshire Hathaway Energy": {
        "title": "What Greg Abel Might Do With Berkshire Hathaway Massive Cash Pile",
        "date": "2026-07-25",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.fool.com/investing/2026/07/25/what-greg-abel-might-do-berkshire-hathaway-cash/?source=iedfolrf0000001",
        "image": "https://g.foolcdn.com/editorial/images/879628/thinking-investor-using-a-laptop-computer.jpg"
    },
    "DAVIDSON KEMPNER": {
        "title": "Davidson Kempner Capital Management LP : Form 8 . 3 - easyJet PLC",
        "date": "2026-07-24",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.manilatimes.net/2026/07/24/tmt-newswire/globenewswire/davidson-kempner-capital-management-lp-form-83-easyjet-plc/2391154",
        "image": "https://www.manilatimes.net/theme_manilatimes/images/TMT_1920x1008.jpg"
    },
    "Kroll, LLC": {
        "title": "UK law firm plunges into administration - £250m loans",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.express.co.uk/news/uk/2233364/uk-law-firm-plunges-administration",
        "image": "https://cdn.images.express.co.uk/img/dynamic/1/1200x630/7064044.jpg"
    },
    "ROCKEFELLER AND COMPANY": {
        "title": "Ministry Announce Final Album  Hate To Go ( Take Out Or Delivery ) And Farewell Tour Dates",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.stereoboard.com/content/view/252322/9",
        "image": "https://www.stereoboard.com/images/artistimages/ministry.jpg"
    },
    "FISHER INVESTMENTS": {
        "title": "Carlyle , Bain in race to buy Wealth Enhancement for $7bn – report",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://finance.yahoo.com/markets/stocks/articles/carlyle-bain-race-buy-wealth-101733595.html",
        "image": "https://s.yimg.com/lo/mysterio/api/AC0FCE7DFAB373254945FC8F019BDAF23D4E494A5E8D710E224EE57A12C8B51B/subgraphmysterio/resizefill_w1200_h675;quality_80;format_webp/https:%2F%2Fmedia.zenfs.com%2Fen%2Fprivate_banker_international_938%2Fbee704efee9fc2e39627aa417f8864b3"
    },
    "AMERIPRISE FINANCIAL INC": {
        "title": "SPDR Bloomberg 3 - 12 Month T - Bill ETF ( NYSEARCA : BILS ) Short Interest Update",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.themarketsdaily.com/2026/07/27/spdr-bloomberg-3-12-month-t-bill-etf-nysearcabils-short-interest-update-2.html",
        "image": ""
    },
    "PRINCIPAL FINANCIAL GROUP": {
        "title": "Algonquin Power & Utilities Corp . $AQN Shares Purchased by Public Employees Retirement System of Ohio",
        "date": "2026-07-26",
        "summary": "",
        "impact": "Potential Copilot opportunity — align outreach to this signal.",
        "level": "Medium",
        "url": "https://www.tickerreport.com/banking-finance/13516164/algonquin-power-utilities-corp-aqn-shares-purchased-by-public-employees-retirement-system-of-ohio.html",
        "image": ""
    },
    "ROBERT W. BAIRD & CO INC": {
        "title": "Weiss Asset Management LP Makes New Investment in Curtiss - Wright Corporation $CW",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.tickerreport.com/banking-finance/13517478/weiss-asset-management-lp-makes-new-investment-in-curtiss-wright-corporation-cw.html",
        "image": ""
    },
    "LAZARD FRERES AND COMPANY": {
        "title": "Lazard advice sought for likely debt buybacks , while debt affordability improves",
        "date": "2026-07-25",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.sundaytimes.lk/260726/news/lazard-advice-sought-for-likely-debt-buybacks-while-debt-affordability-improves-650533.html",
        "image": ""
    },
    "Stone X": {
        "title": "Southside Bancshares ( SBSI ) Q2 2026 Earnings Call Transcript",
        "date": "2026-07-25",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://www.fool.com/earnings/call-transcripts/2026/07/24/southside-bancshares-sbsi-q2-2026-earnings-call-transcript/?source=iedfolrf0000001",
        "image": "https://cdn.content.foolcdn.com/images/1umn9qeh/production/b4204f36ed605fc54d4ba32e2cb31d1dd892afd6-800x450.jpg?&q=75&fit=max&auto=format"
    },
    "VISA U S A INC": {
        "title": "Lands End Visa Credit Card",
        "date": "2026-07-12",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.unitaid.eu/lands-end-visa-credit-card-0etr.html",
        "image": "https://www.unitaid.eu/Themes/agk/assets/agk.jpg"
    },
    "Brookfield Asset Management": {
        "title": "Brookfield commits up to $9 - billion for AI data centre in South Korea",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Potential Azure AI, Fabric opportunity — align outreach to this signal.",
        "level": "Medium",
        "url": "https://www.theglobeandmail.com/business/article-brookfield-commits-up-to-9-billion-for-ai-data-centre-in-south-korea/",
        "image": "https://www.theglobeandmail.com/resizer/v2/DE4A37BFJFEDPAMXXRFT6G5ECQ.jpg?auth=aee7b6948eab67476da6b81aff3b23a9680a0b9bc24bad2ac875448d65173a63&quality=80&smart=true"
    },
    "NORTHERN TRUST CORPORATION": {
        "title": "Northern Trust to provide fund administration services to Dawson Partners",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://www.assetservicingtimes.com/assetservicesnews/fundservicesarticle.php?article_id=18180",
        "image": ""
    },
    "BRIDGEWATER ASSOCIATES": {
        "title": "Dolphins to host QB Jack Plummer for workout",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.sun-sentinel.com/2026/07/25/dolphins-to-host-quarterback-for-workout-report-says/",
        "image": "https://www.sun-sentinel.com/wp-content/uploads/2026/07/tfl-z-AP25239733628379-01.jpg"
    },
    "Fidelity Investments": {
        "title": "Fidelity says retirees now face $185 , 500 in healthcare costs up 7 . 5 % from last year , and long - term care isnt included",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://finance.yahoo.com/healthcare/articles/fidelity-says-retirees-now-face-123000749.html",
        "image": "https://s.yimg.com/lo/mysterio/api/6C8EE79B94AF4FA137A4353419500AF12A0C8C1BA3545B6EDE1DC5B5E4D91564/subgraphmysterio/resizefill_w1200_h675;quality_80;format_webp/https:%2F%2Fmedia.zenfs.com%2Fen%2Fmoneywise_327%2F839133fe2629cebdd891549b83989b5c"
    },
    "Blackstone Inc.": {
        "title": "Japan New Activists Blend McKinsey And Blackstone",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.forbes.com/sites/robertdaugherty/2026/07/27/japans-new-activists-blend-mckinsey-and-blackstone/",
        "image": "https://imageio.forbes.com/specials-images/imageserve/68f7805040311a110b2f928c/0x0.jpg?format=jpg&fit=bounds"
    },
    "BLACKROCK FINANCIAL MANAGEMENT": {
        "title": "Holding ( s ) in Company | Company Announcement",
        "date": "2026-07-17",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.investegate.co.uk/announcement/rns/telecom-plus--tep/holding-s-in-company/9675636",
        "image": ""
    },
    "NASDAQ OMX": {
        "title": "First Trust NASDAQ ABA Community Bank Index Fund ( NASDAQ : QABA ) Trading Up 2 . 8 % – Time to Buy ?",
        "date": "2026-07-17",
        "summary": "",
        "impact": "Potential Fabric opportunity — align outreach to this signal.",
        "level": "High",
        "url": "https://www.dailypolitical.com/2026/07/16/first-trust-nasdaq-aba-community-bank-index-fund-nasdaqqaba-trading-up-2-8-time-to-buy.html",
        "image": ""
    },
    "VANGUARD GROUP INC": {
        "title": "Goldman , T . Rowe Debut Their First Interval Fund for the Masses",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://finance.yahoo.com/markets/stocks/articles/goldman-t-rowe-debut-first-144651698.html",
        "image": "https://s.yimg.com/lo/mysterio/api/757A32E151D009D5D9F51C28B05A50E8E935634A4FF4F3F95138AC66285C55B1/subgraphmysterio/resizefill_w1200_h623;quality_80;format_webp/https:%2F%2Fmedia.zenfs.com%2Fen%2Fwealth_management_474%2F1a8128a925c06e59bb6d0531995e5f73"
    },
    "American National Insurance Co": {
        "title": "Geneva Lou Humberson",
        "date": "2026-07-20",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.therecordlive.com/story/2026/07/22/obituaries/geneva-lou-humberson/38333.html",
        "image": "https://www.therecordlive.com/home/cms_data/dfault/photos/stories/id/3/3/38333/s_top"
    },
    "MUTUAL OF OMAHA": {
        "title": "Omaha City Council agenda notes for July 28",
        "date": "2026-07-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.wowt.com/2026/07/25/omaha-city-council-agenda-notes-july-28/",
        "image": "https://gray-wowt-prod.gtv-cdn.com/resizer/v2/HNGLGZUBPVBDPNKR3HI5QVPEWI.jpg?auth=044400aad55c2180fe6ed211656401c8d802a18a0299baccfbd728db0ddec81f&smart=true"
    },
    "PROSPERITY LIFE GROUP": {
        "title": "Daily Vedic tips to bring peace , prosperity , and positivity",
        "date": "2026-07-14",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://timesofindia.indiatimes.com/astrology/others/daily-vedic-tips-to-bring-peace-prosperity-and-positivity/articleshow/132382317.cms",
        "image": "https://static.toiimg.com/thumb/msid-132382637,width-1280,height-720,resizemode-6,overlay-toi_sw,pt-32,y_pad-600/photo.jpg"
    },
    "Tokio Marine Group": {
        "title": "Prudential May Sell Brazil Unit for US$3 Billion",
        "date": "2026-07-23",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.riotimesonline.com/prudential-may-sell-brazil-unit-for-us3-billion/",
        "image": "https://www.riotimesonline.com/wp-content/uploads/2026/07/1x-1-39.webp"
    },
    "MERCURY INSURANCE COMPANY": {
        "title": "Why Wildfire Risk Can Vary from One Home to the Next",
        "date": "2026-07-23",
        "summary": "",
        "impact": "Potential Security opportunity — align outreach to this signal.",
        "level": "Medium",
        "url": "http://www.prnewswire.com/news-releases/why-wildfire-risk-can-vary-from-one-home-to-the-next-302832958.html",
        "image": ""
    },
    "aflac": {
        "title": "Azzi Fudd becomes first rookie to win WNBA 3 - point contest",
        "date": "2026-07-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.yardbarker.com/wnba/articles/azzi_fudd_becomes_first_rookie_to_win_wnba_3_point_contest/s1_17054_44099297",
        "image": "https://www.yardbarker.com/media/e/1/e16ddd7c115b02de3bdad652691ba495e063b4ef/thumb_16x9/29446812.jpg"
    },
    "AmWINS Group": {
        "title": "Price Forbes adds casualty to Lectio as lead - layer capacity tightens",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.insurancebusinessmag.com/au/news/breaking-news/price-forbes-adds-casualty-to-lectio-as-leadlayer-capacity-tightens-583784.aspx",
        "image": "https://cdn-res.keymedia.com/cms/images/us/023/0356_639207598696133764.jpg"
    },
    "ERIE INSURANCE GROUP": {
        "title": "Local Auto Body Shop Works to Fix Dented Vehicles Following Hail Storm",
        "date": "2026-07-23",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.erienewsnow.com/news/local-auto-body-shop-works-to-fix-dented-vehicles-following-hail-storm/article_99702de3-2fb3-4fe6-98b9-f3c783fbefdf.html",
        "image": "https://bloximages.chicago2.vip.townnews.com/erienewsnow.com/content/tncms/assets/v3/editorial/9/97/99702de3-2fb3-4fe6-98b9-f3c783fbefdf/6a6274297a26e.preview.png?crop=1920%2C1008%2C0%2C35"
    },
    "PROTECTIVE LIFE CORPORATION": {
        "title": "Scientists Say Consciousness Comes From Feelings , Not Thoughts",
        "date": "2026-07-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.popularmechanics.com/science/a73249621/feelings-consciousness-neuroscience/",
        "image": "https://hips.hearstapps.com/hmg-prod/images/fa655cc6-2e0c-4747-a21c-ab4ff6060b86.jpeg?crop=1xw:0.759430604982xh;center,top"
    },
    "Genworth": {
        "title": "Genworth Financial , Inc . $GNW Shares Purchased by Caxton Associates LLP",
        "date": "2026-07-25",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.dailypolitical.com/2026/07/25/genworth-financial-inc-gnw-shares-purchased-by-caxton-associates-llp.html",
        "image": ""
    },
    "LINCOLN NATIONAL CORPORATION": {
        "title": "Time Alone with Abe and Mary : The Abraham Lincoln Museum and Library",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.newcity.com/2026/07/27/time-alone-with-abe-and-mary-the-abraham-lincoln-museum-and-library/",
        "image": "https://www.newcity.com/wp-content/uploads/2026/07/Mural-Reflection-scaled-e1783275924845.jpg"
    },
    "Berkshire Hathaway Specialty Insurance Company": {
        "title": "Women in Insurance Summit Australia 2026 set for August with early bird window closing",
        "date": "2026-07-23",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.insurancebusinessmag.com/au/news/breaking-news/women-in-insurance-summit-australia-2026-set-for-august-with-early-bird-window-closing-583452.aspx",
        "image": "https://cdn-res.keymedia.com/cms/images/us/026/0381_639204019644945895.png"
    },
    "RISK STRATEGIES COMPANY": {
        "title": "Itai Levitan | investingLive",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Potential Azure AI opportunity — align outreach to this signal.",
        "level": "Medium",
        "url": "https://investinglive.com/author/itai-levitan/",
        "image": "https://investinglive.com/author/itai-levitan/images/il-og-thumbnail.png"
    },
    "VERISK ANALYTICS": {
        "title": "GM Is Betting Big on Trucks Again",
        "date": "2026-07-21",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.autoweek.com/news/a73220784/gm-betting-big-on-trucks-again/",
        "image": "https://hips.hearstapps.com/hmg-prod/images/57084e32-ca9c-4628-bf27-158388746da3.png?crop=1xw:0.889xh;0xw,0.111xh"
    },
    "MASSACHUSETTS MUTUAL LIFE INSURANCE COMPANY": {
        "title": "Barings Bdc ( NYSE : BBDC ) Stock Price Up 1 . 3 % – Still a Buy ?",
        "date": "2026-07-17",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.dailypolitical.com/2026/07/16/barings-bdc-nysebbdc-stock-price-up-1-3-still-a-buy.html",
        "image": ""
    },
    "USI INSURANCE": {
        "title": "Captive insurance people moves news | Alera Group hires Dougherty as transportation insurance vice president",
        "date": "2026-07-08",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.captiveinsurancetimes.com/captiveinsurancenews/peoplemovesarticle.php?article_id=10459&navigationaction=latestnews&page=1&newssection=people",
        "image": "https://captiveinsurancetimes.com/captiveinsurancenews/images/WednesdayJuly820261783514595.jpg"
    },
    "Stewart Title Guaranty Company": {
        "title": "The New KYC : Know Your Collateral",
        "date": "2026-07-06",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.mondaq.com:443/unitedstates/real-estate/1812246/the-new-kyc-know-your-collateral",
        "image": "http://www.mondaq.com/images/MondaqThumb.png"
    },
    "BROWN AND BROWN, Inc.": {
        "title": "Survivor of Old Sacramento stabbing shares his story",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.kcra.com/article/survivor-old-sacramento-stabbing-shares-his-story/73267286",
        "image": "https://kubrick.htvapps.com/vidthumb/cd21939b-e81a-4fc6-8599-54d20eee0ad1/962c41ec-b85c-4286-9707-ce5e707aa6e5.jpg"
    },
    "ARTHUR J GALLAGHER & CO": {
        "title": "Gallagher RPS acquires Pennsylvania wholesale broker W . N . Tuscano Agency",
        "date": "2026-07-22",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://www.insurancebusinessmag.com/us/news/excess-surplus/gallaghers-rps-acquires-pennsylvania-wholesale-broker-w-n--tuscano-agency-583198.aspx",
        "image": "https://cdn-res.keymedia.com/cms/images/us/003/0382_639202916280956595.png"
    },
    "Assurant": {
        "title": "Principal Financial Group Inc . Has $14 . 57 Million Stock Holdings in Assurant , Inc . $AIZ",
        "date": "2026-07-24",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.themarketsdaily.com/2026/07/24/principal-financial-group-inc-has-14-57-million-stock-holdings-in-assurant-inc-aiz.html",
        "image": ""
    },
    "FM GLOBAL": {
        "title": "China deeply concerned over escalating situation in Middle East , urges parties concerned to resume dialogue : FM spokesperson",
        "date": "2026-07-24",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.globalsecurity.org/wmd/library/news/iran/2026/07/iran-260723-globaltimes01.htm",
        "image": ""
    },
    "AMERICAN FINANCIAL GROUP INC": {
        "title": "Unum Group ( UNM ) Reports Q2 : Everything You Need To Know Ahead Of Earnings",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://finance.yahoo.com/markets/stocks/articles/unum-group-unm-reports-q2-102102492.html",
        "image": "https://s.yimg.com/lo/mysterio/api/60FA2A0F3C0A91AC9119138215F66C08A4B407BDA2F7EFFCBE5C59C47EFCD439/subgraphmysterio/resizefill_w1200_h600;quality_80;format_webp/https:%2F%2Fmedia.zenfs.com%2Fen%2Fstockstory_922%2Fe294eaa069709f18d332eca803a3427b"
    },
    "JACKSON NATIONAL LIFE": {
        "title": "Prudential Is Well Positioned for Better Dividends and Long - Term Growth",
        "date": "2026-07-21",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://www.morningstar.com/company-reports/1488860-prudential-is-well-positioned-for-better-dividends-and-long-term-growth",
        "image": ""
    },
    "Loews Corp": {
        "title": "Independence Day festivities abound in South Florida",
        "date": "2026-07-24",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://communitynewspapers.com/columnists/gloria%E2%80%99s-gab/independence-day-festivities-abound-in-south-florida/",
        "image": "https://communitynewspapers.com/wp-content/uploads/2026/07/Gab-8017-featured-m.jpg"
    },
    "OLD REPUBLIC INTERNATIONAL": {
        "title": "Old Republic International ( NYSE : ORI ) Releases Quarterly Earnings Results , Misses Expectations By $0 . 03 EPS",
        "date": "2026-07-25",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://www.themarketsdaily.com/2026/07/25/old-republic-international-nyseori-releases-quarterly-earnings-results-misses-expectations-by-0-03-eps.html",
        "image": ""
    },
    "FARM BUREAU FINANCIAL SERVICES": {
        "title": "South Dakota Farm Bureau to host NextGen Beef Tour Aug . 21 - 22 near MItchell",
        "date": "2026-07-23",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://drgnews.com/2026/07/23/south-dakota-farm-bureau-to-host-nextgen-beef-tour-aug-21-22-near-mitchell/",
        "image": "https://media-cdn.socastsrm.com/wordpress/wp-content/blogs.dir/2626/files/2026/07/farm-bureau-south-dakota-nextgen-beef-tour-082126.png"
    },
    "Kemper Corporation": {
        "title": "QPR transfer round - up including Edwards , De Keersmaecker latest",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://the72.co.uk/2026/07/27/qpr-transfer-roundup-edwards-de-keersmaecker-latest/",
        "image": "https://cdn.the72.co.uk/wp-content/uploads/2026/07/prsijgREzdmd.webp"
    },
    "ARCH CAPITAL GROUP LTD": {
        "title": "Meeder Asset Management Inc . Has $1 . 07 Million Stock Position in Arch Capital Group Ltd . $ACGL",
        "date": "2026-07-21",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.dailypolitical.com/2026/07/21/meeder-asset-management-inc-has-1-07-million-stock-position-in-arch-capital-group-ltd-acgl.html",
        "image": ""
    },
    "NEW YORK LIFE INSURANCE COMPANY": {
        "title": "Wealth management advisor Brighton Jones expands to Stamford",
        "date": "2026-07-23",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://westfaironline.com/fairfield/wealth-management-advisor-brighton-jones-expands-to-stamford/",
        "image": "https://westfaironline.com/wp-content/uploads/2026/07/Bennett.png"
    },
    "GUARDIAN LIFE INSURANCE CO": {
        "title": "Musikfest 2026 guide : When , lineup , food , parking and more",
        "date": "2026-07-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.mcall.com/2026/07/26/musikfest-2026-guide-when-lineup-food-parking/",
        "image": "https://www.mcall.com/wp-content/uploads/2025/08/TMC-L-MusikfestNightCrawler-_21-1.jpg"
    },
    "National Life Group": {
        "title": "Platner Is Gone , But His Billionaire Tax Plan Still Matters",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.forbes.com/sites/taxnotes/2026/07/27/platner-is-gone-but-his-billionaire-tax-plan-still-matters/",
        "image": "https://imageio.forbes.com/specials-images/imageserve/6a676773ad8187435b91466d/0x0.jpg?format=jpg&fit=bounds"
    },
    "Nationwide": {
        "title": "Lake Region Healthcare named to Forbe Top Hospitals by State",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://y94.com/2026/07/27/lake-region-healthcare-named-to-forbes-top-hospitals-by-state/",
        "image": "https://media-cdn.socastsrm.com/wordpress/wp-content/blogs.dir/2431/files/2026/07/lake-region-hospital.png"
    },
    "GEICO": {
        "title": "Progressive Sent You $300 . State Farm Is Sending $173 . USAA Sent $760 . GEICO Sent Nothing . Here Why Every Florida Driver Got a Different Answer » Live Insurance News",
        "date": "2026-07-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.liveinsurancenews.com/progressive-state-farm-florida/8574455/",
        "image": "https://www.liveinsurancenews.com/wp-content/uploads/2026/07/Auto-insurance-refunds-1.jpg"
    },
    "ALLSTATE INSURANCE GROUP": {
        "title": "Forbes Daily : LeBron James Takes A Major Pay Cut With The 76ers",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.forbes.com/sites/daniellechemtob/2026/07/27/forbes-daily-lebron-james-takes-a-major-pay-cut-with-the-76ers/",
        "image": "https://imageio.forbes.com/specials-images/imageserve/69049934f8748e598b2e7d15/0x0.jpg?format=jpg&crop=3113,1750,x0,y160,safe&fit=bounds"
    },
    "FIRST AMERICAN FINANCIAL CORP": {
        "title": "Unum Group ( UNM ) Reports Q2 : Everything You Need To Know Ahead Of Earnings",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://finance.yahoo.com/markets/stocks/articles/unum-group-unm-reports-q2-102102492.html",
        "image": "https://s.yimg.com/lo/mysterio/api/60FA2A0F3C0A91AC9119138215F66C08A4B407BDA2F7EFFCBE5C59C47EFCD439/subgraphmysterio/resizefill_w1200_h600;quality_80;format_webp/https:%2F%2Fmedia.zenfs.com%2Fen%2Fstockstory_922%2Fe294eaa069709f18d332eca803a3427b"
    },
    "LIBERTY MUTUAL INSURANCE COMPANY": {
        "title": "Calif . Court Denies Request to Certify Order Finding Coverage for Silica - Related Claims for Interlocutory Appeal",
        "date": "2026-07-21",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.harrismartin.com/publications/10/benzene/articles/96759/calif-court-denies-request-to-certify-order-finding-coverage-for-silica-related-claims-for-interlocutory-appeal/",
        "image": ""
    },
    "PRUDENTIAL INSURANCE CO OF AMERICA": {
        "title": "Lockheed Martin , Verizon to Outsource DB and DC Investments to Goldman Sachs",
        "date": "2026-07-13",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.plansponsor.com/lockheed-martin-verizon-to-outsource-db-and-dc-investments-to-goldman-sachs/",
        "image": "https://si-interactive.s3.amazonaws.com/prod/plansponsor-com/wp-content/uploads/2026/07/09094258/PSPA-070926-Lockheed-Verizon-OCIO-1411644772-web.jpg"
    },
    "Progressive Corporation": {
        "title": "Amy Needs an Icon Costume and The Bobby Bones Show Delivers | Wizard 106 . 7",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://wizard106.iheart.com/featured/bobby-bones/content/2026-07-27-amy-needs-an-icon-costumeand-the-bobby-bones-show-delivers/",
        "image": "https://i.iheart.com/v3/re/new_assets/6a6764e3191ba9220e97dcee?ops=gravity(%22north%22),fit(1200,675),quality(65)"
    },
    "Willis Towers Watson": {
        "title": "Nationwide hires former WTW exec to distribution role",
        "date": "2026-07-22",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.businessinsurance.com/nationwide-hires-former-wtw-exec-to-distribution-role/",
        "image": "https://www.businessinsurance.com/wp-content/uploads/2026/07/Roberto-Robles.jpeg"
    }
}
