"""Per-account news — AUTO-GENERATED by fetch_news.py. Do not hand-edit.
Provider: gdelt. Window: last 30 days. Generated: 2026-07-29 15:41Z.
"""

NEWS = {
    "HILLTOP HOLDINGS": {
        "title": "KJo recalls life - changing conversations with SRK on Guru Purnima",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.siasat.com/kjo-recalls-life-changing-conversations-with-srk-on-guru-purnima-3515323/",
        "image": "https://cdn.siasat.com/wp-content/uploads/2026/07/srk-kjo.jpg"
    },
    "NATIONSTAR MORTGAGE": {
        "title": "Master Sales - Columbia Star",
        "date": "2026-07-23",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.thecolumbiastar.com/articles/masters-sales-303/",
        "image": ""
    },
    "EAST WEST BANCORP INC": {
        "title": "A $550 , 000 Portfolio That Quietly Pays a 62 - Year - Old $3 , 400 a Month Until Social Security Kicks In",
        "date": "2026-07-26",
        "summary": "",
        "impact": "Potential Security opportunity — align outreach to this signal.",
        "level": "Medium",
        "url": "https://finance.yahoo.com/markets/stocks/articles/550-000-portfolio-quietly-pays-195234765.html",
        "image": "https://s.yimg.com/lo/mysterio/api/D93A779C2268C84632CE83FC12B9C4A2CFF9B26BDC1B60E26B27BDB98A5EBD73/subgraphmysterio/resizefill_w1200_h633;quality_80;format_webp/https:%2F%2Fmedia.zenfs.com%2Fen%2F24_7_wall_st__718%2F1971681c16df76d900f15c765694dead"
    },
    "MORTGAGE RESEARCH CENTER": {
        "title": "Current refi mortgage rates report for July 24 , 2026",
        "date": "2026-07-24",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://fortune.com/article/current-refi-mortgage-rates-07-24-2026/",
        "image": "https://fortune.com/img-assets/wp-content/uploads/2026/07/Refi-Rates-July-24.jpg"
    },
    "PINNACLE BANK": {
        "title": "Tickets on Sale Thursday for Volleyball Red - White Scrimmage",
        "date": "2026-07-28",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.mycentralnebraska.com/tickets-on-sale-thursday-for-volleyballs-red-white-scrimmage/",
        "image": ""
    },
    "Guaranteed Rate Inc": {
        "title": "Rate Companies : Where the Best Women in Mortgage Do Their Best Work",
        "date": "2026-07-28",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.manilatimes.net/2026/07/29/tmt-newswire/globenewswire/rate-companies-where-the-best-women-in-mortgage-do-their-best-work/2393433",
        "image": "https://manilatimes.net/manilatimes/uploads/images/2026/07/29/1154940.jpg"
    },
    "ZIONS BANK CORPORATION": {
        "title": "Northern Utah Living : 3 events to check out this week ( July 25 - Aug . 2 ) | News , Sports , Jobs",
        "date": "2026-07-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.standard.net/lifestyle/2026/jul/25/northern-utah-living-3-events-to-check-out-this-week-july-25-aug-2/",
        "image": "https://ogden_images.s3.amazonaws.com/www.standard.net/images/2025/07/31212147/BW_Korn-Ferry-Golf_-020-1200x801.jpg"
    },
    "ARVEST BANK GROUP": {
        "title": "Sei Investments Co . Acquires 846 , 230 Shares of Exelon Corporation $EXC",
        "date": "2026-07-24",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://www.tickerreport.com/banking-finance/13513858/sei-investments-co-acquires-846230-shares-of-exelon-corporation-exc.html",
        "image": ""
    },
    "Movement Mortgage": {
        "title": "Power Moves : CBRE , MBA , TMO and others make key personnel decisions",
        "date": "2026-07-24",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.scotsmanguide.com/news/power-moves-july-6-to-24/",
        "image": "https://www.scotsmanguide.com/files/sites/2/2026/07/Power-Moves-July-6-to-24.jpg"
    },
    "Sagent M&C, LLC": {
        "title": "The Inner Circle acknowledges Connie L . Doyle as a 2026 Pinnacle Professional Member Inner Circle of Excellence",
        "date": "2026-06-30",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.prnewswire.com/news-releases/the-inner-circle-acknowledges-connie-l-doyle-as-a-2026-pinnacle-professional-member-inner-circle-of-excellence-302814783.html",
        "image": "https://mma.prnewswire.com/media/3002553/The_Inner_Circle__Connie_L_Doyle.jpg?p=facebook"
    },
    "Datasite": {
        "title": "RECOMMENDED ACQUISITION OF DCC ENERGY PLC | Company Announcement",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://www.investegate.co.uk/announcement/rns/dcc-energy-plc--dcc/recommended-acquisition-of-dcc-energy-plc/9687627",
        "image": ""
    },
    "Insurity": {
        "title": "Insurity Expands Access to Advanced Risk Intelligence Through Partnership with Confianza",
        "date": "2026-07-21",
        "summary": "",
        "impact": "Potential Security opportunity — align outreach to this signal.",
        "level": "Medium",
        "url": "https://thestarphoenix.com/press-releases/business-wire/insurity-expands-access-to-advanced-risk-intelligence-through-partnership-with-confianza/",
        "image": "https://cts.businesswire.com/ct/CT?id=bwnews&sty=20260721379468r1&sid=cnpm5&distro=ftp"
    },
    "Q2 Software": {
        "title": "I gave Claude Opus 5 and Kimi K3 15 impossible prompts the winner surprised me",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.tomsguide.com/ai/i-gave-claude-opus-5-and-kimi-k3-15-impossible-prompts-the-winner-surprised-me",
        "image": "https://cdn.mos.cms.futurecdn.net/L8cAzghw7MuQ4ngxjca7nf-1672-80.png"
    },
    "ALLY FINANCIAL": {
        "title": "Spending while youre abroad : What you need to know",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://kvia.com/entertainment/stacker-travel/2026/07/29/spending-while-youre-abroad-what-you-need-to-know/",
        "image": "https://kvia.com/wp-content/uploads/2026/07/ally-spending-while-youre-abroad.jpg"
    },
    "OneMain Financial": {
        "title": "Sequoia Financial Advisors LLC Sells 8 , 409 Shares of OneMain Holdings , Inc . $OMF",
        "date": "2026-07-23",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://www.themarketsdaily.com/2026/07/23/sequoia-financial-advisors-llc-sells-8409-shares-of-onemain-holdings-inc-omf.html",
        "image": ""
    },
    "FREDDIE MAC": {
        "title": "BSI Financial Expands Digital Mortgage Capabilities with Ginnie Mae eIssuer and eSubservicer Approvals",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Medium",
        "url": "http://www.prnewswire.com/news-releases/bsi-financial-expands-digital-mortgage-capabilities-with-ginnie-mae-eissuer-and-esubservicer-approvals-302836433.html",
        "image": ""
    },
    "Synchrony Financial": {
        "title": "Sei Investments Co . Has $57 . 41 Million Position in Synchrony Financial $SYF",
        "date": "2026-07-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.themarketsdaily.com/2026/07/26/sei-investments-co-has-57-41-million-position-in-synchrony-financial-syf.html",
        "image": ""
    },
    "WEBSTER BANK": {
        "title": "CVR Partners ( NYSE : UAN ) Share Price Passes Above 200 - Day Moving Average – Should You Sell ?",
        "date": "2026-07-25",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Medium",
        "url": "https://www.dailypolitical.com/2026/07/25/cvr-partners-nyseuan-share-price-passes-above-200-day-moving-average-should-you-sell.html",
        "image": ""
    },
    "FIFTH THIRD BANCORP": {
        "title": "VanEck Morningstar International Moat ETF ( BATS : MOTI ) Short Interest Update",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.dailypolitical.com/2026/07/29/vaneck-morningstar-international-moat-etf-batsmoti-short-interest-update.html",
        "image": ""
    },
    "KeyCorp": {
        "title": "Spartan Wealth Advisory Services LLC Makes New Investment in Alphabet Inc . $GOOGL",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.dailypolitical.com/2026/07/29/spartan-wealth-advisory-services-llc-makes-new-investment-in-alphabet-inc-googl.html",
        "image": ""
    },
    "Columbia Banking System, Inc.": {
        "title": "Walleye Capital LLC Invests $560 , 000 in Columbia Banking System , Inc . $COLB",
        "date": "2026-07-25",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.themarketsdaily.com/2026/07/25/walleye-capital-llc-invests-560000-in-columbia-banking-system-inc-colb.html",
        "image": ""
    },
    "FIRST TECHNOLOGY CREDIT UNION": {
        "title": "Credit Unions Raise Over $1 . 65M To Support Children Health",
        "date": "2026-07-23",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "http://www.prnewswire.com/news-releases/credit-unions-raise-over-1-65m-to-support-childrens-health-302832904.html",
        "image": ""
    },
    "HEALTHEQUITY INC": {
        "title": "Investment Analyst Upgrades for July 25th ( ACIW , ACRE , AEE , AGI , AKAN , ALNY , AMACU , AMBP , APOG , ARCC )",
        "date": "2026-07-25",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.tickerreport.com/banking-finance/13515757/investment-analysts-upgrades-for-july-25th-aciw-acre-aee-agi-akan-alny-amacu-ambp-apog-arcc.html",
        "image": ""
    },
    "Elevate Credit": {
        "title": "Fort Worth - Based Elevate Closes $655 Million Credit Facility to Fuel Next Phase of Growth",
        "date": "2026-07-13",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://fortworthbusiness.com/business/fort-worth-based-elevate-closes-655-million-credit-facility-to-fuel-next-phase-of-growth/",
        "image": ""
    },
    "FACTSET RESEARCH SYSTEMS": {
        "title": "FactSet Research Systems ( NYSE : FDS ) Trading 7 % Higher – What Next ?",
        "date": "2026-07-28",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.dailypolitical.com/2026/07/28/factset-research-systems-nysefds-trading-7-higher-whats-next.html",
        "image": ""
    },
    "GREEN DOT CORPORATION": {
        "title": "Falcons embrace the new era in pre - training camp 53 - man roster prediction",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://bloggingdirty.com/falcons-embrace-the-new-era-in-pre-training-camp-53-man-roster-prediction-01kymv45jdmq",
        "image": "https://images2.minutemediacdn.com/image/upload/c_crop,x_0,y_0,w_5616,h_3159/c_fill,w_1440,ar_1440:810,f_auto,q_auto,g_auto/images/ReutersImages/mmsport/44/01kymv5e46hcp3y966w8.jpg"
    },
    "FANNIE MAE": {
        "title": "BSI Financial Expands Digital Mortgage Capabilities with Ginnie Mae eIssuer and eSubservicer Approvals",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Medium",
        "url": "http://www.prnewswire.com/news-releases/bsi-financial-expands-digital-mortgage-capabilities-with-ginnie-mae-eissuer-and-esubservicer-approvals-302836433.html",
        "image": ""
    },
    "VYSTAR CREDIT UNION": {
        "title": "New  Duuuval Wall mural opens in historic Union Terminal",
        "date": "2026-07-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.actionnewsjax.com/news/local/new-mural-jam-duuuval-walls-opens-historic-downtown-jacksonville-tunnel/LQ2BVISFGBHLFLVJ3FETCC3ITA/",
        "image": "https://cmg-cmg-tv-10050-prod.cdn.arcpublishing.com/resizer/v2/https%3A%2F%2Fcloudfront-us-east-1.images.arcpublishing.com%2Fcmg%2FC7IUKTODZNAWTHQ6GFH2XG4LDU.jpeg?auth=5918317d07c010f1c0d49b92cb05fde6958b24bdbcb163380da3655f1b8230d4&smart=true"
    },
    "CITIZENS FINANCIAL GROUP": {
        "title": "Disclosures show CFPB pick ties to several regulated firms",
        "date": "2026-07-25",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.americanbanker.com/news/disclosures-show-cfpb-picks-ties-to-several-regulated-firms",
        "image": "https://source-media-brightspot.s3.us-east-1.amazonaws.com/df/0c/a24bee6d4db28bc4eed69f8ebe2b/johnsoncfpb.png"
    },
    "United Wholesale Mortgage": {
        "title": "FICO 10T gains momentum as more than 70 lenders join program",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.scotsmanguide.com/news/fico-10t-gains-momentum-as-more-than-70-lenders-join-program/",
        "image": "https://www.scotsmanguide.com/files/sites/2/2026/07/FICO-10T-growing.jpg"
    },
    "FIS Global": {
        "title": "FIS and Anthropic extend partnership - Asset Servicing Times",
        "date": "2026-07-17",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Medium",
        "url": "https://www.assetservicingtimes.com/assetservicesnews/technologyarticle.php?article_id=18158",
        "image": ""
    },
    "NAVY FEDERAL CREDIT UNION M": {
        "title": "Pensacola grandmother nearly falls victim to scam targeting military community",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://weartv.com/news/local/pensacola-grandmother-nearly-falls-victim-to-scam-targeting-military-community",
        "image": "https://weartv.com/resources/media2/16x9/1280/1320/center/90/dc273c82-a6c2-459a-b070-129b2bdf668c-gmamil.png"
    },
    "Citigroup": {
        "title": "Rhino Bitcoin Adds 500 , 000 , 000 Splendor Labs ( SPLD ) Tokens to Corporate Balance Sheet",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.manilatimes.net/2026/07/29/tmt-newswire/globenewswire/rhino-bitcoin-adds-500000000-splendor-labs-spld-tokens-to-corporate-balance-sheet/2394161",
        "image": "https://manilatimes.net/manilatimes/uploads/images/2026/07/29/1156339.png"
    },
    "Bank of America": {
        "title": "401 ( k ) Real Talk Episode 203 : July 29 , 2026",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.wealthmanagement.com/rpa-news/401-k-real-talk-episode-203-july-29-2026",
        "image": "https://eu-images.contentstack.com/v3/assets/bltabaa95ef14172c61/blt91e49ec8546574db/69f35a0f3c5d472a158e4961/401k-real-talk-2026-PROMO-NO-DATE.png?disable=upscale&fit=crop&overlay=%2Fv3%2Fassets%2Fbltabaa95ef14172c61%2Fblt38d05c932b77fe9f%2F6a3931f66deb92be88b595a5%2FWM-OpenGraph_indigo.png&overlay-width=432&overlay-height=166&overlay-align=right,bottom"
    },
    "CITADEL INVESTMENT GROUP": {
        "title": "XFLT Proxy Contest : Why the Board Believes the King Street Sub - Adviser Will Be Beneficial for XFLT Shareholders",
        "date": "2026-07-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.manilatimes.net/2026/07/26/tmt-newswire/globenewswire/xflt-proxy-contest-why-the-board-believes-the-king-street-sub-adviser-will-be-beneficial-for-xflt-shareholders/2391657",
        "image": "https://manilatimes.net/manilatimes/uploads/images/2026/07/26/1151603.png"
    },
    "EDWARD D JONES AND COMPANY": {
        "title": "Edward Jones pushes back on lawsuit challenging diversity program",
        "date": "2026-07-09",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://finance.yahoo.com/small-business/articles/edward-jones-pushes-back-lawsuit-121800705.html",
        "image": "https://s.yimg.com/lo/mysterio/api/122F07CADD6BBC20623DB87F59E5D0C8E0499CE60AEB49632F5E33DFD1E93C88/subgraphmysterio/resizefill_w1200_h675;quality_80;format_webp/https:%2F%2Fmedia.zenfs.com%2Fen%2Fhr_dive_843%2F32b1dec6214085df10ced8550abee0d2"
    },
    "LPL Financial": {
        "title": "LPL Welcomes Sunny Day Financial | The Manila Times",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.manilatimes.net/2026/07/29/tmt-newswire/globenewswire/lpl-welcomes-sunny-day-financial/2394075",
        "image": "https://manilatimes.net/manilatimes/uploads/images/2026/07/29/1156151.jpg"
    },
    "D E SHAW & CO INC": {
        "title": "10 Stocks Lost Over 40 % in 2026 as Investors Dumped Everything AI Might Kill",
        "date": "2026-07-28",
        "summary": "",
        "impact": "Potential Azure AI opportunity — align outreach to this signal.",
        "level": "Medium",
        "url": "https://finance.yahoo.com/markets/stocks/articles/10-stocks-lost-over-40-181945525.html",
        "image": "https://s.yimg.com/lo/mysterio/api/A2E0DADE48D3D6BE9B5DE629E8486FBF5A3671C3C256866B9363FD527530524E/subgraphmysterio/resizefill_w1200_h675;quality_80;format_webp/https:%2F%2Fmedia.zenfs.com%2Fen%2Fbeincrypto_us_662%2Fcc4a1b492d807a16d0991a233e579f47"
    },
    "JEFFERIES & COMPANY INC": {
        "title": "Closing Bell : Nifty Reclaims 24 , 250 as IT Rallies for Third Straight Day and FIIs Turn Net Buyers",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.indiainfoline.com/news/markets/closing-bell-nifty-reclaims-24250-as-it-rallies-for-third-straight-day-and-fiis-turn-net-buyers",
        "image": "https://www.indiainfoline.com/next-assets/image/default-new.webp"
    },
    "Ascensus, Inc.": {
        "title": "Ascensus Launches National 403 ( b ) PEP for Nonprofits",
        "date": "2026-06-30",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://www.plansponsor.com/ascensus-launches-national-403b-pep-for-nonprofits/",
        "image": "https://si-interactive.s3.amazonaws.com/prod/plansponsor-com/wp-content/uploads/2026/06/29201028/PSPA-062926-Ascensus-Announcement-new-PEP-1256382271-web-960x540-1.jpg"
    },
    "WELLINGTON MANAGEMENT COMPANY LLC": {
        "title": "Verra Mobility ( VRRM ) to Release Quarterly Earnings on Wednesday",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://www.dailypolitical.com/2026/07/29/verra-mobility-vrrm-to-release-quarterly-earnings-on-wednesday.html",
        "image": ""
    },
    "DEPOSITORY TRUST CLEARING CORPORATION": {
        "title": "Round - the - clock trading is coming , but retail investors are already there",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.investmentnews.com/equities/round-the-clock-trading-is-coming-but-retail-investors-are-already-there/267554",
        "image": "https://cdn-res.keymedia.com/investmentnews/uploads/2019/10/BLOG12_150909988_AR_-1_YTLKZWFZUQCV-2.jpg"
    },
    "DISCOVER FINANCIAL": {
        "title": "Cramer : this industrial stock faces a do - or - die moment for our investment",
        "date": "2026-07-22",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.cnbc.com/2026/07/22/cramer-this-industrial-stock-faces-a-do-or-die-moment-for-our-investment.html",
        "image": "https://image.cnbcfm.com/api/v1/image/108074550-1733934578548-DOV_Image_5.jpg?v=1733934832"
    },
    "TWO SIGMA INVESTMENTS": {
        "title": "Paycom Software ( PAYC ) to Release Quarterly Earnings on Wednesday",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://www.dailypolitical.com/2026/07/29/paycom-software-payc-to-release-quarterly-earnings-on-wednesday.html",
        "image": ""
    },
    "HARBOURVEST PARTNERS LLC": {
        "title": "Investment Firm HarbourVest Partners Takes 20K SF at 9 West 57th Street – Commercial Observer",
        "date": "2026-07-20",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Medium",
        "url": "https://commercialobserver.com/2026/07/harbourvest-partners-lease-9-west-57th-street/",
        "image": "https://commercialobserver.com/wp-content/uploads/sites/3/2026/07/Alexander-Chudnoff-Howard-Fiddle-9-W-57th-St-credit-Getty-images.jpg?quality=80&crop=0px%2C70px%2C2000px%2C1051px"
    },
    "JANUS HENDERSON GROUP": {
        "title": "Holding ( s ) in Company | Company Announcement",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.investegate.co.uk/announcement/rns/british-land-company--blnd/holding-s-in-company/9694239",
        "image": ""
    },
    "TPG Capital": {
        "title": "Bain Capital acquires Vitabiotics : united kingdom nutraceutical giant with India Meyer Organics valued at $850 - 900 million",
        "date": "2026-07-25",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://economictimes.indiatimes.com/news/international/business/bain-capital-acquires-vitabiotics-uk-nutraceutical-giant-with-indias-meyer-organics-valued-at-850-900-million/articleshow/132614546.cms",
        "image": "https://img.etimg.com/thumb/msid-132614570,width-1200,height-630,imgsize-252729,overlay-economictimes/articleshow.jpg"
    },
    "Berkshire Hathaway Energy": {
        "title": "Meet the Dividend Growth Stock That Warren Buffett Held for Decades , and Greg Abel Pegged as One of Berkshire Hathaway Multidecade Compounders",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://www.fool.com/investing/2026/07/27/meet-the-dividend-growth-stock-that-warren-buffett/?source=iedfolrf0000001",
        "image": "https://g.foolcdn.com/editorial/images/880559/buffett19-tmf.jpg"
    },
    "BERKSHIRE HATHAWAY INC": {
        "title": "2 Billionaires , 1 Stock : Both Have More Than 15 % of Their Portfolios in Amazon",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://finance.yahoo.com/markets/stocks/articles/2-billionaires-1-stock-both-123035342.html",
        "image": "https://s.yimg.com/lo/mysterio/api/00310DA273ADED6D1B5257EB32DFDDB837566AA494D241BD4BD620498A96D1F4/subgraphmysterio/resizefill_w1200_h675;quality_80;format_webp/https:%2F%2Fmedia.zenfs.com%2Fen%2F24_7_wall_st__718%2F8fa4fa683be4dc9735572736a88c5ce5"
    },
    "Guggenheim Partners": {
        "title": "Dodger , Laker Owner Linked to Loan Fraud Probe",
        "date": "2026-07-28",
        "summary": "",
        "impact": "Potential Security opportunity — align outreach to this signal.",
        "level": "Medium",
        "url": "https://790waeb.iheart.com/content/2026-07-28-dodgers-lakers-owner-linked-to-loan-fraud-probe/",
        "image": "https://i.iheart.com/v3/re/assets.getty/6a68bf8e1003898ad1166572?ops=gravity(%22north%22),fit(1200,675),quality(65)"
    },
    "Kroll, LLC": {
        "title": "Christina Lake rallies behind fire rescue boat campaign",
        "date": "2026-07-28",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://grandforksgazette.ca/2026/07/28/christina-lake-rallies-behind-fire-rescue-boat-campaign/",
        "image": "https://grandforksgazette.ca/wp-content/uploads/sites/22/2026/07/ChristinaLakeResuce.jpg"
    },
    "PRINCIPAL FINANCIAL GROUP": {
        "title": "Full Year Results and Publication of Annual Report | Company Announcement",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://www.investegate.co.uk/announcement/rns/great-southern-copper--gscu/full-year-results-and-publication-of-annual-report/9693951",
        "image": ""
    },
    "Stone X": {
        "title": "Southside Bancshares ( SBSI ) Q2 2026 Earnings Call Transcript",
        "date": "2026-07-25",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://www.fool.com/earnings/call-transcripts/2026/07/24/southside-bancshares-sbsi-q2-2026-earnings-call-transcript/?source=iedfolrf0000001",
        "image": "https://cdn.content.foolcdn.com/images/1umn9qeh/production/b4204f36ed605fc54d4ba32e2cb31d1dd892afd6-800x450.jpg?&q=75&fit=max&auto=format"
    },
    "Brookfield Asset Management": {
        "title": "Brookfield Asset Management gets nod to acquire India Oaktree entities",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://www.dealstreetasia.com/stories/brookfield-oaktree-490544",
        "image": "https://cdn.dealstreetasia.com/uploads/2023/11/Love-That-Design-Brookfield-Asset-Management-10-1536x1025-1.jpg?fit=849,615"
    },
    "NORTHERN TRUST CORPORATION": {
        "title": "Spyglass Capital Management LLC Purchases 45 , 919 Shares of AppLovin Corporation $APP",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.dailypolitical.com/2026/07/29/spyglass-capital-management-llc-purchases-45919-shares-of-applovin-corporation-app.html",
        "image": ""
    },
    "PayPal, Inc.": {
        "title": "Binance bStocks Reaches $500 Million in AUM as a New Generation of Investors Turns to Tokenized Stocks",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "http://www.singaporestar.com/news/279214852/binance-bstocks-reaches-500-million-in-aum-as-a-new-generation-of-investors-turns-to-tokenized-stocks",
        "image": ""
    },
    "Blackstone Inc.": {
        "title": "Toronto - area developers pivot toward rentals as condo construction continues to slide",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.theglobeandmail.com/real-estate/article-toronto-rental-apartment-construction-condos-data/",
        "image": "https://www.theglobeandmail.com/pf/resources/assets/meta/facebook-1200x630.png?d=937"
    },
    "S&P Global": {
        "title": "Binance holds the deepest liquidity for nearly two - thirds of listed crypto assets",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.thesouthafrican.com/technology/cryptocurrencies/binance-holds-the-deepest-liquidity-for-nearly-two-thirds-of-listed-crypto-assets/",
        "image": "https://www.thesouthafrican.com/wp-content/uploads/2026/07/Binance.jpg.optimal.jpg"
    },
    "American National Insurance Co": {
        "title": "Geneva Lou Humberson",
        "date": "2026-07-20",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.therecordlive.com/story/2026/07/22/obituaries/geneva-lou-humberson/38333.html",
        "image": "https://www.therecordlive.com/home/cms_data/dfault/photos/stories/id/3/3/38333/s_top"
    },
    "PROSPERITY LIFE GROUP": {
        "title": "JAB Holdings B . V . Announces Pricing of Tender Offers for Any and All of Its 2 . 200 % Senior Notes Due 2030 , 3 . 750 % Senior Notes Due 2051 and 4 . 500 % Sustainability - Linked Senior Notes Due 2052",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.finanznachrichten.de/nachrichten-2026-07/69135878-jab-holdings-b-v-announces-pricing-of-tender-offers-for-any-and-all-of-its-2-200-senior-notes-due-2030-3-750-senior-notes-due-2051-and-4-500-sust-004.htm",
        "image": "https://cts.businesswire.com/ct/CT?id=bwnews&sty=20260727620706r1&sid=gefi2&distro=ftp"
    },
    "Tokio Marine Group": {
        "title": "iWOW Raises S$15 . 0 Million For Next Phase of Growth",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://www.manilatimes.net/2026/07/29/tmt-newswire/media-outreach-newswire/iwow-raises-s150-million-for-next-phase-of-growth/2394022",
        "image": "https://www.manilatimes.net/theme_manilatimes/images/TMT_1920x1008.jpg"
    },
    "UNITED SERVICES AUTOMOBILE ASSOCIATION (USAA)": {
        "title": "Silgan ( NYSE : SLGN ) Releases Q3 2026 Earnings Guidance",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://www.dailypolitical.com/2026/07/29/silgan-nyseslgn-releases-q3-2026-earnings-guidance.html",
        "image": ""
    },
    "MERCURY INSURANCE COMPANY": {
        "title": "Top 10 SUVs That Are The Cheapest to Insure in 2026 and Why Right Now Is One of the Best Times of Year to Actually Go Buy One » Live Insurance News",
        "date": "2026-07-28",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.liveinsurancenews.com/top-10-suvs-cheapest-to-insure/8574565/",
        "image": "https://www.liveinsurancenews.com/wp-content/uploads/2026/07/Untitled20Image-49.jpg"
    },
    "ERIE INSURANCE GROUP": {
        "title": "New Public Art Installation Takes Shape Outside Erie Insurance Arena",
        "date": "2026-07-28",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.erienewsnow.com/news/new-public-art-installation-takes-shape-outside-erie-insurance-arena/article_e4ded15d-d9d9-4339-a2c8-a78249c945da.html",
        "image": "https://bloximages.chicago2.vip.townnews.com/erienewsnow.com/content/tncms/assets/v3/editorial/f/0e/f0ea09a4-c3fa-5115-b46d-931db55365d6/6a67d709d13a3.image.jpg?crop=1280%2C672%2C0%2C23"
    },
    "PROTECTIVE LIFE CORPORATION": {
        "title": "Scientists Say Consciousness Comes From Feelings , Not Thoughts",
        "date": "2026-07-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.popularmechanics.com/science/a73249621/feelings-consciousness-neuroscience/",
        "image": "https://hips.hearstapps.com/hmg-prod/images/fa655cc6-2e0c-4747-a21c-ab4ff6060b86.jpeg?crop=1xw:0.759430604982xh;center,top"
    },
    "ASSURED PARTNERS": {
        "title": "Miss Malawi 2025 Thandi Chisi Calls for Patience Amid Ongoing Public Debate",
        "date": "2026-07-28",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.faceofmalawi.com/2026/07/28/miss-malawi-2025-thandi-chisi-calls-for-patience-amid-ongoing-public-debate/",
        "image": "https://www.faceofmalawi.com/wp-content/uploads/2026/07/Miss-Malawi.jpg"
    },
    "Genworth": {
        "title": "How Much Would A Public Long - Term Care Insurance Program Cost ?",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.forbes.com/sites/howardgleckman/2026/07/27/how-much-would-a-public-long-term-care-insurance-program-cost/",
        "image": "https://imageio.forbes.com/specials-images/imageserve/6a67c1f898c74544f11fd6f2/0x0.jpg?format=jpg&fit=bounds"
    },
    "Berkshire Hathaway Specialty Insurance Company": {
        "title": "Women in Insurance Summit Australia 2026 set for August with early bird window closing",
        "date": "2026-07-23",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.insurancebusinessmag.com/au/news/breaking-news/women-in-insurance-summit-australia-2026-set-for-august-with-early-bird-window-closing-583452.aspx",
        "image": "https://cdn-res.keymedia.com/cms/images/us/026/0381_639204019644945895.png"
    },
    "HARTFORD FIRE INSURANCE COMPANY": {
        "title": "The Hartford sues Dallas firm over unpaid worker comp premiums",
        "date": "2026-07-22",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.insurancebusinessmag.com/us/news/risk-compliance-legal/the-hartford-sues-dallas-firm-over-unpaid-workers-comp-premiums-583282.aspx",
        "image": "https://cdn-res.keymedia.com/cms/images/us/003/0343_639203398561818237.png"
    },
    "RISK STRATEGIES COMPANY": {
        "title": "Inogen Alliance : From Water Risk to Water Resilience : Five Themes Shaping the Future of Water Stewardship",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Potential Security opportunity — align outreach to this signal.",
        "level": "Medium",
        "url": "https://www.finanznachrichten.de/nachrichten-2026-07/69156530-inogen-alliance-from-water-risk-to-water-resilience-five-themes-shaping-the-future-of-water-stewardship-200.htm",
        "image": "https://app.accessnewswire.com/imagelibrary/8f60f4b6-b0ad-4f00-872b-75ab3034721d/1197970/56e4d17f-8fe2-4ba1-807c-6bdebcad0c8e.png?v=1"
    },
    "MASSACHUSETTS MUTUAL LIFE INSURANCE COMPANY": {
        "title": "Barings Bdc ( NYSE : BBDC ) Stock Price Up 1 . 3 % – Still a Buy ?",
        "date": "2026-07-17",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.dailypolitical.com/2026/07/16/barings-bdc-nysebbdc-stock-price-up-1-3-still-a-buy.html",
        "image": ""
    },
    "The Hanover Insurance Group": {
        "title": "Hanover posts record Q2 income with 91 . 2 % combined ratio",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://www.insurancebusinessmag.com/us/news/breaking-news/hanover-posts-record-q2-income-with-91-2-combined-ratio-584148.aspx",
        "image": "https://cdn-res.keymedia.com/cms/images/us/003/0359_639209185276438805.jpg"
    },
    "USI INSURANCE": {
        "title": "Hoover City Council OKs extra $5 million in tax rebates for Stadium Trace Village",
        "date": "2026-07-28",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://280living.com/news/hoover-city-council-oks-extra-5-million-in-tax-rebates-for-s/",
        "image": "https://280living.com/downloads/40505/download/Stadium%20Trace%20Village%20%281%29%20copy.jpg?cb=07f674cfa0fdb8f8145b9678aa438807"
    },
    "REINSURANCE GROUP OF AMERICA": {
        "title": "PNC Financial Services Group Inc . Trims Stock Holdings in Reinsurance Group of America , Incorporated $RGA",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.dailypolitical.com/2026/07/29/pnc-financial-services-group-inc-trims-stock-holdings-in-reinsurance-group-of-america-incorporated-rga.html",
        "image": ""
    },
    "MARKEL": {
        "title": "Eagles training camp preview : 53 - man roster prediction",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.bleedinggreennation.com/philadelphia-eagles-roster/178055/eagles-training-camp-preview-53-man-roster-prediction",
        "image": "https://platform.bleedinggreennation.com/wp-content/uploads/sites/36/2026/07/gettyimages-2253357344.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613"
    },
    "AAA INSURANCE GROUP": {
        "title": "Non - life insurers rebound on strong first - half results",
        "date": "2026-07-24",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://vir.com.vn/non-life-insurers-rebound-on-strong-first-half-results-157383.html",
        "image": "https://vir.com.vn/stores/news_dataimages/2026/072026/24/14/in_social/non-life-insurers-rebound-on-strong-first-half-results-translated-20260724145155.jpg?randTime=1784894435"
    },
    "STANDARD INSURANCE CO": {
        "title": "Increasing resilience across an interlinked financial system",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Potential Security opportunity — align outreach to this signal.",
        "level": "Medium",
        "url": "https://www.actuarialpost.co.uk/article/increasing-resilience-across-an-interlinked-financial-system-26989.htm",
        "image": ""
    },
    "ACRISURE LLC": {
        "title": "Steelers report to training camp in Latrobe today | WISR 680 AM – Butler , PA",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://wisr680.com/steelers-report-to-training-camp-in-latrobe-today/",
        "image": ""
    },
    "OLD REPUBLIC INTERNATIONAL": {
        "title": "Old Republic International ( NYSE : ORI ) Releases Quarterly Earnings Results , Misses Expectations By $0 . 03 EPS",
        "date": "2026-07-25",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://www.themarketsdaily.com/2026/07/25/old-republic-international-nyseori-releases-quarterly-earnings-results-misses-expectations-by-0-03-eps.html",
        "image": ""
    },
    "SHELTER INSURANCE COMPANY": {
        "title": "What to Do After a House Fire : A Step - by - Step Recovery Guide",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.gigwise.com/what-to-do-after-a-house-fire-a-step-by-step-recovery-guide/",
        "image": "https://www.gigwise.com/wp-content/uploads/2026/07/what-to-do-after-a-house-fire-a-step-by-step-recovery-guide.webp"
    },
    "NEW YORK LIFE INSURANCE COMPANY": {
        "title": "Wealth management advisor Brighton Jones expands to Stamford",
        "date": "2026-07-23",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://westfaironline.com/fairfield/wealth-management-advisor-brighton-jones-expands-to-stamford/",
        "image": "https://westfaironline.com/wp-content/uploads/2026/07/Bennett.png"
    },
    "EQUITABLE": {
        "title": "NEP at six : Is India education system ready for the AI age ?",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Potential Azure AI opportunity — align outreach to this signal.",
        "level": "Medium",
        "url": "https://www.hindustantimes.com/ht-insight/future-tech/nep-at-six-is-indias-education-system-ready-for-the-ai-age-101785331690992.html",
        "image": ""
    },
    "National Life Group": {
        "title": "Dr Doug Hilton At National Press Club",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.miragenews.com/dr-doug-hilton-at-national-press-club-1718179/",
        "image": "https://www.csiro.au/-/media/Owned-articles/2026/07-July/Press-Club/Dr-Doug-Hilton-press-club-open-arms.jpg?mw=1200&hash=C14A674A90BEA3B35774635A4C78A114"
    },
    "TRAVELERS PROPERTY & CASUALTY": {
        "title": "As insurance rates fall , tort reform takes much - deserved victory lap",
        "date": "2026-07-06",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.times-herald.com/opinion/as-insurance-rates-fall-tort-reform-takes-much-deserved-victory-lap/article_0c0550bb-275e-4e47-8a9f-6cfab218f0bd.html",
        "image": "https://bloximages.chicago2.vip.townnews.com/times-herald.com/content/tncms/assets/v3/editorial/a/e3/ae341c82-42c8-11ef-a0f5-a750425da974/6695508b8205a.image.jpg"
    },
    "Nationwide": {
        "title": "COAS appoints GOCs for new Army divisions",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Medium",
        "url": "https://tribuneonlineng.com/coas-appoints-gocs-for-new-army-divisions/",
        "image": "https://tribuneonlineng.com/wp-content/uploads/2026/07/IMG-20260521-WA0190.jpg"
    },
    "GEICO": {
        "title": "Female athletes surge in NIL deals as Learfield reports a 123 % jump in participation",
        "date": "2026-07-28",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://toronto.citynews.ca/2026/07/28/female-athletes-surge-in-nil-deals-as-learfield-reports-a-123-jump-in-participation/",
        "image": "https://toronto.citynews.ca/wp-content/blogs.dir/sites/10/2026/07/007680ec0126a400a82915d18e6a054cba79e7a36224a0aed0adac502fea883b.jpg"
    },
    "Marsh McLennan": {
        "title": "Marsh & McLennan ( MRSH ) Reinvents Operations with AI Productivity Push",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Potential Azure AI, Copilot opportunity — align outreach to this signal.",
        "level": "Medium",
        "url": "https://finance.yahoo.com/markets/stocks/articles/marsh-mclennan-mrsh-reinvents-operations-132051970.html",
        "image": "https://s.yimg.com/lo/mysterio/api/5040E8C71DCDA54EBD59A1A4843F752D6EED2C2A41E421C024D7AC7E4011B2F8/subgraphmysterio/resizefill_w1200_h672;quality_80;format_webp/https:%2F%2Fmedia.zenfs.com%2Fen%2Finsidermonkey.com%2Fb5928cd57b4b6fc7fcd6b58676ca83c2"
    },
    "Metlife": {
        "title": "BTS Will Not Submit Music for 2027 Grammys , Saying Their Music Shouldnt Be Divided by Region or Language",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://thenet.ng/bts-will-not-submit-music-for-2027-grammys-saying-their-music-shouldnt-be-divided-by-region-or-language/",
        "image": "https://thenet.ng/wp-content/uploads/2026/07/BTS.jpeg"
    },
    "Chubb": {
        "title": "Dolphins veteran RB workout raises new questions about the running back room",
        "date": "2026-07-29",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://phinphanatic.com/miami-dolphins-veteran-rb-workout-raises-new-questions-about-the-running-back-room-01kyncxvcadr",
        "image": "https://images2.minutemediacdn.com/image/upload/c_crop,x_1495,y_31,w_4111,h_2312/c_fill,w_1440,ar_1440:810,f_auto,q_auto,g_auto/images/ReutersImages/mmsport/62/01kynd096wg1rq1m82ad.jpg"
    },
    "Willis Towers Watson": {
        "title": "Unclear risks drive excess data center coverage : Willis",
        "date": "2026-07-28",
        "summary": "",
        "impact": "Potential Fabric, Security opportunity — align outreach to this signal.",
        "level": "Medium",
        "url": "https://www.businessinsurance.com/unclear-risks-drive-excess-data-center-coverage-willis/",
        "image": "https://www.businessinsurance.com/wp-content/uploads/2023/03/cropped-BI-square-blue.png"
    }
}
