"""Per-account news — AUTO-GENERATED by fetch_news.py. Do not hand-edit.
Provider: gdelt. Window: last 30 days. Generated: 2026-08-26 16:47Z.
"""

NEWS = {
    "NATIONSTAR MORTGAGE": {
        "title": "Insurer accuses telephone - harassment litigant of running  extortion scheme",
        "date": "2026-08-21",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.insurancebusinessmag.com/us/news/risk-compliance-legal/insurer-accuses-telephoneharassment-litigant-of-running-extortion-scheme-586927.aspx",
        "image": "https://cdn-res.keymedia.com/cms/images/us/003/0311_639228588696515034.png"
    },
    "FREEDOM MORTGAGE CORPORATION": {
        "title": "Events roundup : Plenty of fun activities on tap in summer waning days – The Times Herald",
        "date": "2026-08-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.timesherald.com/2026/08/26/events-roundup-plenty-of-fun-activities-on-tap-in-summers-waning-days/",
        "image": "https://www.timesherald.com/wp-content/uploads/2026/08/AP26162494554469.jpg"
    },
    "Navient": {
        "title": "Sallie Mae Borrower Loan Went From $84K to $252K : Now She Must Choose Between Rent and Student Debt",
        "date": "2026-08-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.ibtimes.co.uk/sallie-mae-borrower-loan-balance-triples-1816347",
        "image": "https://d.ibtimes.co.uk/en/full/1828192/student-loan-charge-off.jpg"
    },
    "Midland Credit Management": {
        "title": "Public Notices - Columbia Star",
        "date": "2026-08-20",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.thecolumbiastar.com/articles/public-notices-1836/",
        "image": ""
    },
    "PINNACLE BANK": {
        "title": "Education briefs for 8 - 18 - 26",
        "date": "2026-08-18",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://cdispatch.com/news/education-briefs-for-8-18-26/",
        "image": ""
    },
    "South State Bank": {
        "title": "Heart 4 Winter Haven Wants Zero Homeless Children by 2030 Winter Haven",
        "date": "2026-08-11",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://dailyridge.com/2024/07/05/heart-4-winter-haven-wants-zero-homeless-children-by-2030/",
        "image": ""
    },
    "loanDepot": {
        "title": "Jarren Duran hits grand slam in 11th inning to power Red Sox past Marlins",
        "date": "2026-08-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.bostonherald.com/2026/08/25/jarren-duran-hits-grand-slam-in-11th-inning-to-power-red-sox-past-marlins/",
        "image": "https://www.bostonherald.com/wp-content/uploads/2026/08/GettyImages-2292063345.jpg"
    },
    "Experian": {
        "title": "Student Loan Scams 2026 : How To Protect Yourself",
        "date": "2026-08-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.cnbc.com/select/student-loan-scams-2026-how-to-protect-yourself/",
        "image": "https://image.cnbcfm.com/api/v1/image/108352057-1787226044628-gettyimages-2218507020-1t8a5855.jpeg?v=1787755254"
    },
    "FACTSET RESEARCH SYSTEMS": {
        "title": "196 , 176 Shares in FactSet Research Systems Inc . $FDS Purchased by Heron Bay Capital Management",
        "date": "2026-08-22",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.tickerreport.com/banking-finance/13554072/196176-shares-in-factset-research-systems-inc-fds-purchased-by-heron-bay-capital-management.html",
        "image": ""
    },
    "FANNIE MAE": {
        "title": "Better , Coinbase make token - backed mortgages broadly available",
        "date": "2026-08-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.housingwire.com/articles/better-coinbase-token-backed-conforming-mortgage-coinbase-one-credit/",
        "image": "https://www.housingwire.com/wp-content/uploads/2026/08/Conceptual_photoreal_im-e1787683178193.png"
    },
    "Valley National Bank": {
        "title": "Valley National Bancorp Accelerates Growth in Attractive Chicago Market With Acquisition of High - Performing Providence Financial Corporation",
        "date": "2026-08-25",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://www.manilatimes.net/2026/08/25/tmt-newswire/globenewswire/valley-national-bancorp-accelerates-growth-in-attractive-chicago-market-with-acquisition-of-high-performing-providence-financial-corporation/2411750",
        "image": "https://manilatimes.net/manilatimes/uploads/images/2026/08/25/1189662.png"
    },
    "Capital One": {
        "title": "Namibia Capital Market Not Fully Unlocked - The Villager Newspaper",
        "date": "2026-08-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.thevillager.com.na/national/2026/namibias-capital-market-not-fully-unlocked/",
        "image": "https://www.thevillager.com.na/wp-content/uploads/2025/09/capital.jpeg"
    },
    "Bank of America": {
        "title": "Ex - manager accused of stealing $33 , 000 from Flanigan",
        "date": "2026-08-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.local10.com/news/local/2026/08/26/ex-manager-accused-of-stealing-33000-from-flanigans/",
        "image": "https://www.local10.com/resizer/v2/JJS3CF2NRJGVDPU4NR7RGJLTR4.jpg?auth=8e5fbf7eef910788028157a3ad03e933c7eb1a5d75fdd10994275bc79f8747e1"
    },
    "TRUIST FINANCIAL": {
        "title": "Oklo ( NYSE : OKLO ) Stock Price Down 5 . 5 % – Should You Sell ?",
        "date": "2026-08-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.themarketsdaily.com/2026/08/26/oklo-nyseoklo-stock-price-down-5-5-should-you-sell.html",
        "image": ""
    },
    "STATE STREET BOSTON CORPORATION": {
        "title": "QUOTE BOX – Investor reactions to Senate hearing for Fed chair candidate Kevin Warsh",
        "date": "2026-08-24",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://mix929.com/2026/04/21/quote-box-investor-reactions-to-senate-hearing-for-fed-chair-candidate-kevin-warsh/",
        "image": "https://storage.googleapis.com/media.mwcradio.com/mimesis/2026-04/21/2026-04-21T171050Z_1_LYNXMPEM3K134_RTROPTP_3_USA-FED-WARSH.JPG"
    },
    "Apollo Management": {
        "title": "How Should Investors Read the Mixed Signals Coming From Private Markets ?",
        "date": "2026-08-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.morningstar.com/stocks/how-should-investors-read-mixed-signals-coming-private-markets",
        "image": "https://media.morningstar.com/resizer/v2/JXOZE775X5DGZKQJKJZ5VFGHNQ.png?auth=0dfaae1ccc7c00e37590fb594ee7202e8a15c978246612ab6c679272a5033a30&quality=80&crop=0,0:2400,1350"
    },
    "Dun & Bradstreet Corporation": {
        "title": "Agentic AI : Google Cloud Rolls Out Gemini Enterprise For Financial Services",
        "date": "2026-08-26",
        "summary": "",
        "impact": "Potential Azure AI opportunity — align outreach to this signal.",
        "level": "Medium",
        "url": "https://www.crowdfundinsider.com/2026/08/301772-agentic-ai-google-cloud-rolls-out-gemini-enterprise-for-financial-services/",
        "image": "https://www.crowdfundinsider.com/wp-content/uploads/2019/07/Google-London.jpg"
    },
    "D E SHAW & CO INC": {
        "title": "This Generator Stock Has Been Crushed . But Data Center Orders Just Became a $1 Billion Growth Story",
        "date": "2026-08-26",
        "summary": "",
        "impact": "Potential Fabric opportunity — align outreach to this signal.",
        "level": "Medium",
        "url": "https://finance.yahoo.com/markets/stocks/articles/generator-stock-crushed-data-center-180716353.html",
        "image": "https://s.yimg.com/lo/mysterio/api/7998f5ed3e21e7fffa988b214a9f89296fa59bbe8f576bd9970b897e1ca66036/lightyear_networkapi/resizefill_w1200%3Bquality_80%3Bformat_webp/https%3A%2F%2Fmedia.zenfs.com%2Fen%2Finsidermonkey.com%2F9ad8313057c9004ce09bb5d02bd99077.jpg"
    },
    "NEUBERGER BERMAN": {
        "title": "India seeks deeper Japanese investment across sectors , pitches GIFT City as gateway for cross - border capital flows",
        "date": "2026-08-25",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "http://www.asiabulletin.com/news/279263744/india-seeks-deeper-japanese-investment-across-sectors-pitches-gift-city-as-gateway-for-cross-border-capital-flows",
        "image": "https://image.chitra.live/api/v1/wps/f98aaf7/0483b37e-f5d5-4cb9-b5ac-d60c5b0f3715/0/ANI-20260825055348-600x315.jpg"
    },
    "WELLINGTON MANAGEMENT COMPANY LLC": {
        "title": "Chewy ( CHWY ) Outperform Rating Reiterated at Royal Bank Of Canada",
        "date": "2026-08-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Medium",
        "url": "https://www.themarketsdaily.com/2026/08/26/chewys-chwy-outperform-rating-reiterated-at-royal-bank-of-canada.html",
        "image": ""
    },
    "DEPOSITORY TRUST CLEARING CORPORATION": {
        "title": "Why become a Gator ? Here why freshmen said  ye - The Independent Florida Alligator",
        "date": "2026-08-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.alligator.org/article/2026/08/why-become-a-gator-here-s-why-freshmen-said-yes",
        "image": "https://snworksceo.imgix.net/ufa/2f9c9188-352b-491a-9b0a-4cbe951dc700.sized-1000x1000.jpg?&dpr=2&ar=16%3A9&fit=crop&crop=faces"
    },
    "TWO SIGMA INVESTMENTS": {
        "title": "Ondas ( NASDAQ : ONDS ) Trading Down 5 . 4 % – Here Why",
        "date": "2026-08-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.themarketsdaily.com/2026/08/26/ondas-nasdaqonds-trading-down-5-4-heres-why.html",
        "image": ""
    },
    "BROWN BROTHERS HARRIMAN AND COMPANY": {
        "title": "Delek US ( NYSE : DK ) Director Sells $142 , 100 . 00 in Stock",
        "date": "2026-08-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://www.dailypolitical.com/2026/08/25/delek-us-nysedk-director-sells-142100-00-in-stock.html",
        "image": ""
    },
    "Guggenheim Partners": {
        "title": "Dodgers Sends  Fire Sale  Message After $1 . 2 Billion Deal",
        "date": "2026-08-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://www.forbes.com/sites/peterchawaga/2026/08/26/dodgers-sends-fire-sale-message-after-12-billion-deal/",
        "image": "https://imageio.forbes.com/specials-images/imageserve/6915d2ab086cdbec6ce8410d/0x0.jpg?format=jpg&fit=bounds"
    },
    "Kroll, LLC": {
        "title": "BHG Financial Closes a New ABS Transaction of $432 Million",
        "date": "2026-08-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.pr-inside.com/bhg-financial-closes-a-new-abs-transaction-of-432-million-r5216418.htm",
        "image": ""
    },
    "First Advantage Corporation": {
        "title": "Blinkit expands beyond metros in India quick - commerce market race",
        "date": "2026-08-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.business-standard.com/industry/news/blinkit-expands-beyond-metros-in-india-s-quick-commerce-market-race-126082601002_1.html",
        "image": "https://bsmedia.business-standard.com/_media/bs/img/article/2024-09/10/thumb/fitandfill/1200X628/1725954794-2911.jpg"
    },
    "PRINCIPAL FINANCIAL GROUP": {
        "title": "Sanctuary Advisors LLC Invests $3 . 80 Million in Hubbell Inc $HUBB",
        "date": "2026-08-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.themarketsdaily.com/2026/08/26/sanctuary-advisors-llc-invests-3-80-million-in-hubbell-inc-hubb.html",
        "image": ""
    },
    "ROBERT W. BAIRD & CO INC": {
        "title": "McDonald ( MCD ) – Analyst Weekly Ratings Updates",
        "date": "2026-08-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Medium",
        "url": "https://www.themarketsdaily.com/2026/08/26/mcdonalds-mcd-analysts-weekly-ratings-updates.html",
        "image": ""
    },
    "WILLIAM BLAIR & COMPANY": {
        "title": "LandBridge ( NYSE : LB ) Shares Up 4 . 6 % – Here Why",
        "date": "2026-08-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.themarketsdaily.com/2026/08/26/landbridge-nyselb-shares-up-4-6-heres-why.html",
        "image": ""
    },
    "CHARLES SCHWAB CORP": {
        "title": "Salim Ramji Vanguard strikes $4 billion deal to buy wealth platform Altruist : Report",
        "date": "2026-08-26",
        "summary": "",
        "impact": "Potential Fabric opportunity — align outreach to this signal.",
        "level": "High",
        "url": "https://www.livemint.com/companies/news/salim-ramji-s-vanguard-strikes-4-billion-deal-to-buy-wealth-platform-altruist-11787753034929.html",
        "image": "https://www.livemint.com/lm-img/img/2026/08/26/600x338/vanguard_1787754779322_1787754787575_680d38ad-e112-4be0-b000-9afac8bdb7c3.png"
    },
    "VISA U S A INC": {
        "title": "Comenity Bank Lands End Visa",
        "date": "2026-07-27",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.unitaid.eu/comenity-bank-lands-end-visa-v6a3.html",
        "image": "https://www.unitaid.eu/Themes/agk/assets/agk.jpg"
    },
    "GOLDMAN SACHS & COMPANY": {
        "title": "The SEC has subpoenaed four banks over Situational Awareness",
        "date": "2026-08-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Medium",
        "url": "https://thenextweb.com/news/sec-subpoenas-banks-situational-awareness-leverage",
        "image": "https://media.thenextweb.com/2026/08/Leopold-Aschenbrenner.jpg"
    },
    "Blackstone Inc.": {
        "title": "How Mid - Market Advisory Firms Can Win Against Big Names In Audit",
        "date": "2026-08-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Medium",
        "url": "https://www.forbes.com/councils/forbesbusinesscouncil/2026/08/26/how-mid-market-advisory-firms-can-win-a-three-front-war-against-big-names-in-audit/",
        "image": "https://imageio.forbes.com/specials-images/imageserve/68deadd2fff90e2e3b1c9d30/0x0.jpg?format=jpg&fit=bounds"
    },
    "MUTUAL OF OMAHA": {
        "title": "Volunteers lead community initiative marking 25 years since 9 / 11",
        "date": "2026-08-22",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.ketv.com/article/volunteers-heartland-honors-911-25-years-since-sept-11-terror-attacks/73500008",
        "image": "https://kubrick.htvapps.com/vidthumb/87802dcd-a98e-4321-8e20-e1aa368315b0/1ed5ebe7-2162-41f3-89c3-81effde4bb68.jpg?crop=0.671xw%3A0.671xh%3B0.164xw%2C0.130xh"
    },
    "UNITED SERVICES AUTOMOBILE ASSOCIATION (USAA)": {
        "title": "Abercrombie & Fitch ( NYSE : ANF ) Releases Q3 2026 Earnings Guidance",
        "date": "2026-08-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://www.themarketsdaily.com/2026/08/26/abercrombie-fitch-nyseanf-releases-q3-2026-earnings-guidance.html",
        "image": ""
    },
    "MERCURY INSURANCE COMPANY": {
        "title": "10 Tips to Vacation - Proof Your Home While Youre Away",
        "date": "2026-08-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.tigersroar.com/online_features/family_living/article_78094b01-3044-59b3-9d4c-2ce6a2e8c817.html",
        "image": "https://bloximages.chicago2.vip.townnews.com/tigersroar.com/content/tncms/assets/v3/editorial/2/5d/25d8e728-e8ea-5573-a717-1c1ce9c7d0fd/6a79717eaab11.image.jpg?crop=650%2C341%2C0%2C24"
    },
    "RISK STRATEGIES COMPANY": {
        "title": "Dangerous offender granted day parole after 2009 attacks",
        "date": "2026-08-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.insidehalton.com/news/dangerous-offender-gets-parole-caledon/article_405f2904-095a-56c5-b95f-c10361546558.html",
        "image": "https://bloximages.chicago2.vip.townnews.com/insidehalton.com/content/tncms/assets/v3/editorial/d/1e/d1efa931-cf2a-5cf4-8652-b0503017a705/6a8e0c232304d.image.jpg?crop=1661%2C872%2C0%2C180"
    },
    "SELECTIVE INSURANCE": {
        "title": "Deutsche Bank AG Takes Position in Selective Insurance Group , Inc . $SIGI",
        "date": "2026-08-22",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.dailypolitical.com/2026/08/22/deutsche-bank-ag-takes-position-in-selective-insurance-group-inc-sigi.html",
        "image": ""
    },
    "VERISK ANALYTICS": {
        "title": "Verisk Analytics , Inc . ( NASDAQ : VRSK ) Receives $236 . 27 Consensus Price Target from Analysts",
        "date": "2026-08-24",
        "summary": "",
        "impact": "Potential Fabric, Security opportunity — align outreach to this signal.",
        "level": "Medium",
        "url": "https://www.tickerreport.com/banking-finance/13555803/verisk-analytics-inc-nasdaqvrsk-receives-236-27-consensus-price-target-from-analysts.html",
        "image": ""
    },
    "The Hanover Insurance Group": {
        "title": "The Hanover Insurance Group ( NYSE : THG ) Price Target Raised to $240 . 00",
        "date": "2026-08-22",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.dailypolitical.com/2026/08/21/the-hanover-insurance-group-nysethg-price-target-raised-to-240-00-2.html",
        "image": ""
    },
    "Corebridge Financial": {
        "title": "Corebridge Financial ( NYSE : CRBG ) and Suncorp Group ( OTCMKTS : SNMYF ) Head to Head Review",
        "date": "2026-08-22",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.dailypolitical.com/2026/08/22/corebridge-financial-nysecrbg-and-suncorp-group-otcmktssnmyf-head-to-head-review.html",
        "image": ""
    },
    "REINSURANCE GROUP OF AMERICA": {
        "title": "Fiat Ventures combines venture and advisory divisions into new brand , raises $35M Fund II",
        "date": "2026-08-25",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://finance.yahoo.com/small-business/articles/fiat-ventures-combines-venture-advisory-123737988.html",
        "image": "https://s.yimg.com/lo/mysterio/api/7BF2A1A4C0FE2E7908DB322BC2529FD100CBE63EC21FF25E19F63C72A3A69339/subgraphmysterio/resizefill_w1200_h800;quality_80;format_webp/https:%2F%2Fmedia.zenfs.com%2Fen%2Ftechcrunch_finance_785%2F39ac4f5a12672f8262d5566b7eead597.jpg"
    },
    "BROWN AND BROWN, Inc.": {
        "title": "Coverys Appoints Walter Grote as Chief Underwriting Officer",
        "date": "2026-08-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Medium",
        "url": "https://www.manilatimes.net/2026/08/26/tmt-newswire/globenewswire/coverys-appoints-walter-grote-as-chief-underwriting-officer/2412611",
        "image": "https://manilatimes.net/manilatimes/uploads/images/2026/08/26/1191210.png"
    },
    "AMERICAN FAMILY CORPORATION": {
        "title": "33 best dog - friendly wineries in Sonoma County",
        "date": "2026-08-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.eastbaytimes.com/2026/08/26/best-dog-friendly-wineries-in-sonoma-county/",
        "image": "https://www.eastbaytimes.com/wp-content/uploads/2026/08/c9a34126-5116-5c89-aaf0-1db30e0abddb.jpg"
    },
    "Assurant": {
        "title": "Financial Analysis : Assurant ( NYSE : AIZ ) versus Assicurazioni Generali ( OTCMKTS : ARZGF )",
        "date": "2026-08-16",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.themarketsdaily.com/2026/08/16/financial-analysis-assurant-nyseaiz-versus-assicurazioni-generali-otcmktsarzgf.html",
        "image": ""
    },
    "GENERAL REINSURANCE COMPANY": {
        "title": "Berkshire Hathaway Hits an 8 Month High . It Now My Top Buy and Hold Forever Pick .",
        "date": "2026-08-04",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://finance.yahoo.com/markets/stocks/articles/berkshire-hathaway-hits-8-month-121005151.html",
        "image": "https://s.yimg.com/lo/mysterio/api/529C4C36394F27128D378121D125A8C89A39DE039A2F5F9825D6A654D94949AF/subgraphmysterio/resizefill_w1200_h898;quality_80;format_webp/https:%2F%2Fmedia.zenfs.com%2Fen%2F24_7_wall_st__718%2F036453f007fb0a2249137024358aa1df"
    },
    "AMERICAN FINANCIAL GROUP INC": {
        "title": "American Medinas : Turning US Cities Into  Beachhead for Islam",
        "date": "2026-08-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.realclearinvestigations.com/articles/2026/08/26/american_medinas_turning_us_cities_into_beachheads_for_islam_1202481.html",
        "image": "https://assets.realclear.com/images/72/725243_6_.jpeg"
    },
    "FARM BUREAU FINANCIAL SERVICES": {
        "title": "The great farming transition is on the horizon and farm families should be prepared",
        "date": "2026-08-24",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.agweek.com/farm-finances/the-great-farming-transition-is-on-the-horizon-and-farm-families-should-be-prepared",
        "image": "https://forum-communications-production-web.s3.us-west-2.amazonaws.com/brightspot/95/7c/5f374e2341a9b4b1af89d77565da/herbold-swalwell.jpeg"
    },
    "SHELTER INSURANCE COMPANY": {
        "title": "Nonprofits treat hundreds of kids to back - to - school shopping spree after fires",
        "date": "2026-08-24",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "High",
        "url": "https://www.spokesman.com/stories/2026/aug/24/nonprofits-treat-hundreds-of-kids-to-back-to-schoo/",
        "image": "https://thumb.spokesman.com/W4I2i76WBenOQoLxKkKqNNyMQMs=/2400x1260/smart/media.spokesman.com/photos/2026/08/23/6a8a52e168248.hires.jpg"
    },
    "AMYNTA GROUP": {
        "title": "Supervisors approve purchasing VFIS insurance for volunteer firefighters",
        "date": "2026-08-18",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://meridianstar.com/2026/08/18/supervisors-approve-purchasing-vfis-insurance-for-volunteer-firefighters/",
        "image": "https://meridianstar.com/wp-content/uploads/sites/12/2025/07/The-Meridian-Star.png"
    },
    "ARCH CAPITAL GROUP LTD": {
        "title": "BGL Real Estate Team Advises Miller Industries on Build - to - Suit Financing with TPG",
        "date": "2026-08-25",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "http://www.prnewswire.com/news-releases/bgls-real-estate-team-advises-miller-industries-on-build-to-suit-financing-with-tpg-302859616.html",
        "image": ""
    },
    "C V STARR": {
        "title": "Disunion : The Final Q & A",
        "date": "2026-08-04",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://archive.nytimes.com/opinionator.blogs.nytimes.com/2015/06/10/disunion-the-final-q-a/",
        "image": ""
    },
    "National Life Group": {
        "title": "UPDATED : 2027 : I will bring back petrol subsidy , Atiku insists",
        "date": "2026-08-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.premiumtimesng.com/news/top-news/905388-updated-2027-i-will-bring-back-petrol-subsidy-atiku-insists.html",
        "image": "https://media.premiumtimesng.com/wp-content/files/2026/08/HPxiYyGXgAI09Yu-e1787697045255.jpg"
    },
    "TRAVELERS PROPERTY & CASUALTY": {
        "title": "The Docket : Local court roundup for 8 . 6 . 26 - Richmond BizSense",
        "date": "2026-08-06",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://richmondbizsense.com/2026/08/06/the-docket-local-court-roundup-for-8-6-26/",
        "image": "https://richmondbizsense.com/wp-content/uploads/2017/04/stock-henricoCounty-court2.jpg"
    },
    "NORTHWESTERN MUTUAL": {
        "title": "Man Group plc Takes $70 . 13 Million Position in Nucor Corporation $NUE",
        "date": "2026-08-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.themarketsdaily.com/2026/08/26/man-group-plc-takes-70-13-million-position-in-nucor-corporation-nue.html",
        "image": ""
    },
    "Metlife": {
        "title": "Brighthouse Financial , Inc . ( NASDAQ : BHFAM ) Sees Large Drop in Short Interest",
        "date": "2026-08-26",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://www.tickerreport.com/banking-finance/13559840/brighthouse-financial-inc-nasdaqbhfam-sees-large-drop-in-short-interest.html",
        "image": ""
    },
    "PRUDENTIAL INSURANCE CO OF AMERICA": {
        "title": "Public Notices 8 / 21 / 2026",
        "date": "2026-08-22",
        "summary": "",
        "impact": "Account-planning context; no direct solution-play signal detected.",
        "level": "Low",
        "url": "https://thebusinessjournal.com/public-notices-8-21-2026/",
        "image": ""
    },
    "Progressive Corporation": {
        "title": "Jewish High Holy Day Services at Congregation Bnai Harim at the Nevada County Jewish Community Center",
        "date": "2026-08-26",
        "summary": "",
        "impact": "Potential Azure AI opportunity — align outreach to this signal.",
        "level": "Medium",
        "url": "https://yubanet.com/regional/jewish-high-holy-day-services-at-congregation-bnai-harim-at-the-nevada-county-jewish-community-center/",
        "image": "https://i0.wp.com/yubanet.com/wp-content/uploads/2026/08/Unrolling-the-Torah-for-Simchat-Torah-scaled.jpg?fit=1920%2C2560&ssl=1"
    }
}
