# FY26 FSI account rosters (authoritative mapping sourced from WorkIQ / M365 Copilot)
# Structure: top_folder -> sub_folder -> [accounts]

ROSTERS = {
    "Banking": {
        "Banking Majors": [
            "Caliber Funding LLC", "FHLB OF DALLAS", "FROST NATIONAL BANK", "HILLTOP HOLDINGS",
            "NATIONSTAR MORTGAGE", "Texas Capital Bank", "WOODFOREST NATIONAL BANK", "COMERICA INC",
            "FAIRWAY MORTGAGE ACCOUNT OFC", "FREEDOM MORTGAGE CORPORATION",
            "GREYSTONE SERVICING CORP", "Navient", "NORTHWEST SAVINGS BANK",
            "Roundpoint Mortgage Servicing", "CARRINGTON MORTGAGE SERVICE", "EAST WEST BANCORP INC",
            "Midland Credit Management", "MORTGAGE RESEARCH CENTER", "PINNACLE BANK",
            "UNITED MISSOURI BANCSHARES INC", "WESTERN UNION", "BCU", "Guaranteed Rate Inc",
            "MOUNTAIN AMERICA CREDIT UNION", "Old National Bancorp", "TRANS UNION CORPORATION",
            "Wintrust Financial Corporation", "ZIONS BANK CORPORATION", "ARVEST BANK GROUP",
            "Co-op Financial Services", "EXETER FINANCE CORP", "Movement Mortgage",
            "REGIONS FINANCIAL CORPORATION", "REPUBLIC FINANCE",
            "Simmons First National Bank Corporation", "Advisor360", "defi Auto, LLC",
            "Global Payments", "RAPID ADVANCE LLC", "Sagent M&C, LLC", "Versana LLC",
            "APPLIED SYSTEMS INC", "Bloomberg LP", "Datasite", "Insurity", "Q2 Software",
            "ALLY FINANCIAL", "BAYVIEW FINANCIAL", "Eastdil Secured, L.L.C.", "FNB CORPORATION",
            "South State Bank", "State Employees Credit Union", "SYNOVUS FINANCIAL CORP", "Alight",
            "DOVENMUEHLE MORTGAGE INC", "OneMain Financial", "Rock Holding Inc.",
            "Select Portfolio Servicing, Inc.", "AUTOBOOKS", "Flagstar Bank", "FREDDIE MAC",
            "Synchrony Financial", "WEBSTER BANK", "Edfinancial Services", "FIFTH THIRD BANCORP",
            "FIRST HORIZON BANK", "HUNTINGTON BANCSHARES INC", "KeyCorp",
            "Boeing Employees Credit Union", "Columbia Banking System, Inc.",
            "CU DIRECT LENDING (CUDL Technology Center)", "FIRST TECHNOLOGY CREDIT UNION",
            "HEALTHEQUITY INC", "loanDepot", "DUCK CREEK TECHNOLOGIES INC", "Experian", "NELNET",
            "Elevate Credit", "FACTSET RESEARCH SYSTEMS", "GREEN DOT CORPORATION",
            "Jack Henry & Associates Inc.", "FANNIE MAE", "FIRST CITIZENS BANK & TRUST COMPANY",
            "LENDINGTREE.COM", "VYSTAR CREDIT UNION", "CENLAR FSB INC",
            "CITIZENS FINANCIAL GROUP", "COMENITY SERVICES LLC", "M & T BANK",
            "United Wholesale Mortgage", "Valley National Bank",
        ],
        "Banking Strategic": [
            "FIS Global", "NAVY FEDERAL CREDIT UNION", "FIDELITY NATIONAL FINANCIAL",
            "FISERV Inc", "TRUIST FINANCIAL", "Wells Fargo & Company", "US BANK",
            "STATE STREET BOSTON CORPORATION", "Dayforce US, Inc", "BNY Mellon",
            "JPMORGAN CHASE",
            "P N C FINANCIAL CORP", "Citigroup", "Capital One", "Bank of America",
        ],
    },
    "Capital Market": {
        "Capital Market Majors": [
            "CITADEL INVESTMENT GROUP", "EDWARD D JONES AND COMPANY", "S A C CAPITAL ADVISORS LLC",
            "TIAA CREF", "Apollo Management", "BAIN CAPITAL LLC", "KOHLBERG KRAVIS ROBERTS & CO LLC",
            "PLATINUM EQUITY LLC", "Dun & Bradstreet Corporation", "INVESCO",
            "Raymond James and Associates Inc", "Resurgent Capital Services",
            "CITCO TECHNOLOGY MANAGEMENT INC", "Federated Investors", "Intercontinentalexchange",
            "LPL Financial", "D E SHAW & CO INC", "gmo", "Ion Trading", "JEFFERIES & COMPANY INC",
            "MSCI Inc", "NEUBERGER BERMAN", "Ascensus, Inc.", "FINRA", "SUSQUEHANNA PARTNERS G P",
            "T ROWE PRICE ASSOCIATES", "WELLINGTON MANAGEMENT COMPANY LLC",
            "BGC PARTNERS", "Trading Group, LLC", "MORNINGSTAR INC", "STIFEL NICHOLAS & CO INC",
            "Toppan Merrill LLC", "DEPOSITORY TRUST CLEARING CORPORATION", "DISCOVER FINANCIAL",
            "Fortress Investment Group", "Securian", "TWO SIGMA INVESTMENTS",
            "Balyasny Asset Management", "BROWN BROTHERS HARRIMAN AND COMPANY",
            "Chicago mercantile Exchange", "Commonwealth Financial Network", "HARBOURVEST PARTNERS LLC",
            "JANUS HENDERSON GROUP", "ANTARES CAPITAL", "CARLYLE", "CERBERUS CAPITAL MANAGEMENT LP",
            "TPG Capital", "Berkshire Hathaway Energy", "BERKSHIRE HATHAWAY INC", "DAVIDSON KEMPNER",
            "Guggenheim Partners", "Kroll, LLC", "MOODYS INVESTORS SERVICE", "ROCKEFELLER AND COMPANY",
            "First Advantage Corporation", "FISHER INVESTMENTS", "FRANKLIN ADMINISTRATIVE SERVICES",
            "The Capital Group Companies, Inc.", "Voya Services Company", "AMERIPRISE FINANCIAL INC",
            "PRINCIPAL FINANCIAL GROUP", "ROBERT W. BAIRD & CO INC", "WILLIAM BLAIR & COMPANY",
            "LAZARD FRERES AND COMPANY", "LOUIS DREYFUS CORP", "SEI CORP", "Stone X",
        ],
        "Capital Markets Strategic": [
            "CHARLES SCHWAB CORP", "VISA U S A INC", "Brookfield Asset Management",
            "NORTHERN TRUST CORPORATION", "PayPal, Inc.", "AMERICAN EXPRESS COMPANY",
            "BRIDGEWATER ASSOCIATES", "Fidelity Investments", "GOLDMAN SACHS & COMPANY",
            "Blackstone Inc.", "BLACKROCK FINANCIAL MANAGEMENT", "NASDAQ OMX", "S&P Global",
            "MasterCard International", "MORGAN STANLEY", "VANGUARD GROUP INC",
        ],
    },
    "Insurance": {
        "Insurance Majors": [
            "American National Insurance Co", "Berkshire Hathaway Direct Insurance Company",
            "MUTUAL OF OMAHA", "PROSPERITY LIFE GROUP", "Tokio Marine Group",
            "UNITED SERVICES AUTOMOBILE ASSOCIATION (USAA)", "AAA AUTO CLUB ENTERPRISES",
            "AMERICAN FIDELITY", "MERCURY INSURANCE COMPANY", "PACIFIC LIFE INSURANCE CO",
            "SOUTHERN FARM BUREAU CASUALTY", "Southern Farm Bureau Life Insurance Co Inc", "aflac",
            "AmWINS Group", "ERIE INSURANCE GROUP", "GEORGIA FARM BUREAU MUTUAL INS", "Guard Insurance",
            "NSM Insurance Group", "PROTECTIVE LIFE CORPORATION", "ASSURED PARTNERS", "Genworth",
            "LINCOLN NATIONAL CORPORATION", "TIH Insurance Holdings, LLC",
            "Berkshire Hathaway Specialty Insurance Company", "HARTFORD FIRE INSURANCE COMPANY",
            "RISK STRATEGIES COMPANY", "SELECTIVE INSURANCE", "VERISK ANALYTICS",
            "MASSACHUSETTS MUTUAL LIFE INSURANCE COMPANY",
            "SOMPO JAPAN INSURANCE COMPANY OF AMERICA YASUDA INSURANCE", "The Hanover Insurance Group",
            "USI INSURANCE", "W R BERKLEY CORPORATION", "Corebridge Financial",
            "REINSURANCE GROUP OF AMERICA", "Sedgwick Claims Management Services, Inc.",
            "Stewart Title Guaranty Company", "ASURION INSURANCE SERVICES INC", "BROWN AND BROWN, Inc.",
            "MARKEL", "AAA INSURANCE GROUP", "Milliman USA", "STANDARD INSURANCE CO",
            "AMERICAN FAMILY CORPORATION", "ARTHUR J GALLAGHER & CO", "TRUSTMARK INSURANCE COMPANY",
            "AEGON USA", "AMTrust Financial Services INC", "Assurant", "COUNTRY FINANCIAL SERVICES INC",
            "AXIS SPECIALTY US SERVICES INC", "FM GLOBAL", "GENERAL REINSURANCE COMPANY",
            "U N U M LIFE INSURANCE COMPANY", "AAA AUTO CLUB INSURANCE ASSOCIATION", "ACRISURE LLC",
            "AMERICAN FINANCIAL GROUP INC", "CINCINNATI INSURANCE COMPANIES", "CNO Services, LLC",
            "JACKSON NATIONAL LIFE", "CUNA MUTUAL INSURANCE SOCIETY", "Jewelers Mutual Insurance",
            "Loews Corp", "OLD REPUBLIC INTERNATIONAL", "SENTRY INSURANCE A MUTUAL CO",
            "FARM BUREAU FINANCIAL SERVICES", "Hub International", "Kemper Corporation",
            "LOCKTON INSURANCE AGENCY", "SHELTER INSURANCE COMPANY", "AMYNTA GROUP",
            "ARCH CAPITAL GROUP LTD", "C V STARR", "EVEREST GLOBAL SERVICES",
            "NEW YORK LIFE INSURANCE COMPANY", "QBE REINSURANCE SYDNEY REINSURANCE",
            "TRANSATLANTIC REINSURANCE", "EQUITABLE", "GUARDIAN LIFE INSURANCE CO",
            "National Life Group", "TRAVELERS PROPERTY & CASUALTY",
        ],
        "Insurance Strategic": [
            "Nationwide", "GEICO", "STATE FARM LIFE INSURANCE CO", "NORTHWESTERN MUTUAL",
            "Marsh McLennan", "Metlife", "American International Group Inc", "ALLSTATE INSURANCE GROUP",
            "FIRST AMERICAN FINANCIAL CORP", "Aon Corporation", "Chubb",
            "LIBERTY MUTUAL INSURANCE COMPANY", "PRUDENTIAL INSURANCE CO OF AMERICA",
            "Progressive Corporation", "Willis Towers Watson",
        ],
    },
}
