# FY26 FSI account rosters (authoritative mapping sourced from WorkIQ / M365 Copilot)
# Structure: top_folder -> sub_folder -> [accounts]

ROSTERS = {
    "Banking": {
        "Banking Majors": [
            "REGIONS FINANCIAL CORPORATION", "REPUBLIC FINANCE", "EXETER FINANCE CORP",
            "Simmons First National Bank", "ARVEST BANK GROUP", "Movement Mortgage",
            "Velera (Co-op Financial Services)", "Sagent M&C LLC", "Q2 Software",
            "defi Auto LLC", "Versana LLC", "RAPID ADVANCE LLC", "Advisor360",
            "FHLB OF DALLAS", "Texas Capital Bank", "WOODFOREST NATIONAL BANK",
            "HILLTOP HOLDINGS", "FROST NATIONAL BANK", "NATIONSTAR MORTGAGE",
            "New Rez (Caliber Funding) LLC", "Bloomberg LP", "Global Payments",
            "Insurity", "APPLIED SYSTEMS INC", "Datasite", "ZIONS BANK CORPORATION",
            "BCU", "TRANS UNION CORPORATION", "Wintrust Financial", "Old National Bancorp",
            "Guaranteed Rate Inc", "MOUNTAIN AMERICA CREDIT UNION", "Experian", "Alight",
            "OneMain Financial", "ALLY FINANCIAL", "Select Portfolio Servicing",
            "DOVENMUEHLE MORTGAGE", "Midland Credit Management", "Nelnet",
            "UNITED MISSOURI BANCSHARES", "EAST WEST BANCORP", "MORTGAGE RESEARCH CENTER",
            "CARRINGTON MORTGAGE SERVICE", "PINNACLE BANK", "WESTERN UNION",
            "Rock Holding Inc.", "SYNOVUS FINANCIAL CORP", "State Employees Credit Union",
            "BAYVIEW FINANCIAL", "FNB CORPORATION", "Eastdil Secured LLC", "South State Bank",
        ],
        "Banking Strategic": [
            "FIS Global", "NAVY FEDERAL CREDIT UNION", "FIDELITY NATIONAL FINANCIAL",
            "FISERV Inc", "TRUIST FINANCIAL", "Wells Fargo & Company", "US BANK",
            "STATE STREET BOSTON CORPORATION", "Dayforce US Inc", "BNY Mellon",
            "JPMORGAN CHASE", "P N C FINANCIAL CORP", "Citigroup", "Capital One",
            "Bank of America",
        ],
    },
    "Capital Market": {
        "Capital Market Majors": [
            "CITADEL INVESTMENT GROUP", "EDWARD D JONES AND COMPANY", "S A C CAPITAL ADVISORS LLC",
            "TIAA CREF", "Apollo Management", "BAIN CAPITAL LLC", "KOHLBERG KRAVIS ROBERTS & CO LLC",
            "PLATINUM EQUITY LLC", "Dun & Bradstreet Corporation", "INVESCO",
            "Raymond James and Associates Inc", "Resurgent Capital Services",
            "CITCO TECHNOLOGY MANAGEMENT INC", "Federated Investors", "Intercontinentalexchange",
            "LPL Financial", "BGC PARTNERS Trading Group LLC", "MORNINGSTAR INC",
            "STIFEL NICHOLAS & CO INC", "Toppan Merrill LLC", "DEPOSITORY TRUST CLEARING CORPORATION",
            "DISCOVER FINANCIAL", "Fortress Investment Group", "Securian", "TWO SIGMA INVESTMENTS",
            "Balyasny Asset Management", "BROWN BROTHERS HARRIMAN AND COMPANY",
            "Chicago mercantile Exchange", "Commonwealth Financial Network", "HARBOURVEST PARTNERS LLC",
            "JANUS HENDERSON GROUP", "D E SHAW & CO INC", "gmo", "Ion Trading",
            "JEFFERIES & COMPANY INC", "MSCI Inc", "NEUBERGER BERMAN", "Ascensus Inc.",
            "FINRA", "SUSQUEHANNA PARTNERS G P", "T ROWE PRICE ASSOCIATES",
            "WELLINGTON MANAGEMENT COMPANY LLC", "ANTARES CAPITAL", "CARLYLE",
            "CERBERUS CAPITAL MANAGEMENT LP", "TPG Capital", "Berkshire Hathaway Energy",
            "BERKSHIRE HATHAWAY INC", "DAVIDSON KEMPNER", "Guggenheim Partners", "Kroll LLC",
            "MOODYS INVESTORS SERVICE", "ROCKEFELLER AND COMPANY", "First Advantage Corporation",
            "FISHER INVESTMENTS", "FRANKLIN ADMINISTRATIVE SERVICES",
            "The Capital Group Companies Inc.", "Voya Services Company", "AMERIPRISE FINANCIAL INC",
        ],
        "Capital Markets Strategic": [
            "CHARLES SCHWAB CORP", "VISA U S A INC", "Brookfield Asset Management",
            "NORTHERN TRUST CORPORATION", "PayPal Inc.", "AMERICAN EXPRESS COMPANY",
            "BRIDGEWATER ASSOCIATES", "Fidelity Investments", "GOLDMAN SACHS & COMPANY",
            "S&P Global", "MasterCard International", "MORGAN STANLEY", "VANGUARD GROUP INC",
            "Blackstone Inc.", "BLACKROCK FINANCIAL MANAGEMENT", "NASDAQ OMX",
        ],
    },
    "Insurance": {
        "Insurance Majors": [
            "American National Insurance", "Berkshire Hathaway Direct Insurance", "MUTUAL OF OMAHA",
            "PROSPERITY LIFE GROUP", "Tokio Marine Group", "USAA", "AAA AUTO CLUB ENTERPRISES",
            "AMERICAN FIDELITY", "MERCURY INSURANCE", "PACIFIC LIFE", "SOUTHERN FARM BUREAU CASUALTY",
            "Southern Farm Bureau Life", "aflac", "AmWINS Group", "ERIE INSURANCE",
            "GEORGIA FARM BUREAU MUTUAL", "Guard Insurance", "NSM Insurance Group",
            "PROTECTIVE LIFE", "ASSURED PARTNERS", "Genworth", "LINCOLN NATIONAL",
            "TIH Insurance Holdings", "Berkshire Hathaway Specialty", "HARTFORD FIRE",
            "RISK STRATEGIES", "SELECTIVE INSURANCE", "VERISK ANALYTICS", "MASSACHUSETTS MUTUAL",
            "SOMPO JAPAN", "The Hanover Insurance Group", "USI INSURANCE", "W R BERKLEY",
            "AMYNTA GROUP", "ARCH CAPITAL GROUP", "C V STARR", "EVEREST GLOBAL SERVICES",
            "NEW YORK LIFE", "QBE REINSURANCE", "TRANSATLANTIC REINSURANCE", "EQUITABLE",
            "GUARDIAN LIFE", "National Life Group", "TRAVELERS PROPERTY & CASUALTY",
            "AAA AUTO CLUB INSURANCE ASSOCIATION", "ACRISURE LLC", "AMERICAN FINANCIAL GROUP",
            "CINCINNATI INSURANCE", "CNO Services", "JACKSON NATIONAL LIFE", "CUNA MUTUAL",
            "Jewelers Mutual", "Loews Corp", "OLD REPUBLIC INTERNATIONAL", "SENTRY INSURANCE",
            "FARM BUREAU FINANCIAL SERVICES", "Hub International", "Kemper Corporation",
            "LOCKTON INSURANCE", "SHELTER INSURANCE", "Corebridge Financial",
            "REINSURANCE GROUP OF AMERICA", "Sedgwick Claims Management", "Stewart Title Guaranty",
            "ASURION INSURANCE", "BROWN AND BROWN", "MARKEL", "AAA INSURANCE GROUP",
            "Milliman USA", "STANDARD INSURANCE CO", "AMERICAN FAMILY CORPORATION",
            "ARTHUR J GALLAGHER & CO", "TRUSTMARK INSURANCE", "AEGON USA",
            "AMTrust Financial Services", "Assurant", "COUNTRY FINANCIAL SERVICES",
            "AXIS SPECIALTY US SERVICES", "FM GLOBAL",
        ],
        "Insurance Strategic": [
            "Nationwide", "GEICO", "STATE FARM LIFE INSURANCE", "NORTHWESTERN MUTUAL",
            "Marsh McLennan", "MetLife", "American International Group (AIG)",
            "ALLSTATE INSURANCE GROUP", "FIRST AMERICAN FINANCIAL", "Aon Corporation", "Chubb",
            "LIBERTY MUTUAL", "PRUDENTIAL INSURANCE", "Progressive Corporation",
            "Willis Towers Watson",
        ],
    },
}
